---
{{- $policyName := "policy-global-observability-secrets" }}
{{- $policyNamespace := .Values.policy_namespace }}

{{- if .Values.hubClusterSets }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $policyName }}
  namespace: {{ $policyNamespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management, CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration, CA-7 Continuous Monitoring
spec:
{{ if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{ end }}
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: global-observability-rollup-secret
        spec:
          remediationAction: enforce
          severity: high
          evaluationInterval:
            compliant: {{ ((($.Values.autoshift).evaluationInterval).compliant) | default "10m" }}
            noncompliant: {{ ((($.Values.autoshift).evaluationInterval).noncompliant) | default "30s" }}
          object-templates-raw: |
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ $.Values.globalObservability.spokeAgent.globalHubRollup.secretName }}
                  namespace: {{ $.Values.policy_namespace }}
                type: Opaque
                data:
                  tls.crt: '{{ "{{" }} fromSecret "open-cluster-management-observability" "observability-controller-open-cluster-management.io-observability-signer-client-cert" "tls.crt" {{ "}}" }}'
                  tls.key: '{{ "{{" }} fromSecret "open-cluster-management-observability" "observability-controller-open-cluster-management.io-observability-signer-client-cert" "tls.key" {{ "}}" }}'
                  ca.crt: '{{ "{{" }} fromSecret "open-cluster-management-observability" "observability-managed-cluster-certs" "ca.crt" {{ "}}" }}'
                stringData:
                  observatorium.url: 'https://{{ "{{" }} ((lookup "route.openshift.io/v1" "Route" "open-cluster-management-observability" "observatorium-api" | default dict).spec).host {{ "}}" }}/api/metrics/v1/default/api/v1/receive'
{{ end }}
