# This policy suppresses the PodDisruptionBudgetAtLimit alert for the NooBaa
# CNPG primary PDB, which is expected to always have 0 allowed disruptions.
#
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-noobaa-pdb-alert
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
{{ if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{ end }}
  dependencies:
    - name: policy-odf-operator-install
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: noobaa-pdb-alert-relabel
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: monitoring.openshift.io/v1
                kind: AlertRelabelConfig
                metadata:
                  name: suppress-noobaa-pdb-at-limit
                  namespace: openshift-monitoring
                spec:
                  configs:
                    - sourceLabels: [alertname, namespace, poddisruptionbudget]
                      regex: "PodDisruptionBudgetAtLimit;openshift-storage;noobaa-db-pg-cluster-primary"
                      action: Drop
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-noobaa-pdb-alert
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/odf'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-noobaa-pdb-alert
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-noobaa-pdb-alert
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-noobaa-pdb-alert
    apiGroup: policy.open-cluster-management.io
    kind: Policy
