# This policy verifies the installation of the official & supported version of
# the Compliance Operator on the managed clusters.
#
# If set to "enforce" it'll install the operator.
#
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-odf-operator-install
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
{{ if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{ end }}
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: odf-operator-ns
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ .Values.odf.namespace }}
                  labels:
                    openshift.io/cluster-monitoring: "true"
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-odf-operator
        spec:
          remediationAction: enforce
          severity: high
          complianceType: musthave
          operatorGroup:
            # if operator group exists in namespace use that
            name: '{{ "{{" }} with (lookup "operators.coreos.com/v1" "OperatorGroup" "{{ .Values.odf.namespace }}" "").items {{ "}}" }}{{ "{{" }} (index . 0).metadata.name {{ "}}" }}{{ "{{" }} else {{ "}}" }}{{ .Values.odf.namespace }}{{ "{{" }} end {{ "}}" }}'
            namespace: {{ .Values.odf.namespace }}
            targetNamespaces:
              - {{ .Values.odf.namespace }}
          subscription:
            name: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/odf-subscription-name" | default "{{ .Values.odf.name }}" {{ "hub}}" }}'
            namespace: {{ .Values.odf.namespace }}
            # Source Selection Logic (evaluated on hub for each managed cluster):
            # 1. If cluster has explicit 'autoshift.io/odf-source' label → use that value
            # 2. Else if cluster has 'autoshift.io/disconnected-mirror: true':
            #    → use {source}{suffix} (e.g., redhat-operators-mirror)
            #    → suffix from 'autoshift.io/mirror-catalog-suffix' label, or default '-mirror'
            # 3. Else → use standard source (e.g., redhat-operators)
            source: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/odf-source" | default (ternary (printf "%s-%s" "{{ .Values.odf.source }}" (index .ManagedClusterLabels "autoshift.io/mirror-catalog-suffix" | default "mirror")) "{{ .Values.odf.source }}" (eq (index .ManagedClusterLabels "autoshift.io/disconnected-mirror") "true")) {{ "hub}}" }}'
            sourceNamespace: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/odf-source-namespace" | default "{{ .Values.odf.sourceNamespace }}" {{ "hub}}" }}'
            channel: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/odf-channel" | default "{{ .Values.odf.channel }}" {{ "hub}}" }}'
            startingCSV: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/odf-version" | default "" {{ "hub}}" }}'
            # Upgrade approval for subscription will be set based on if version is set not this flag
            # If version is set install plan is set to manual and only the version specified will be installed
          upgradeApproval: Automatic
          versions:
            - '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/odf-version" | default "" {{ "hub}}" }}'
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: odf-status
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: ClusterServiceVersion
                metadata:
                  namespace: {{ .Values.odf.namespace }}
                spec:
                  displayName: OpenShift Data Foundation
                status:
                  phase: Succeeded # check the csv status to determine if operator is running or not
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-odf-operator-install
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/odf'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-odf-operator-install
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-odf-operator-install
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-odf-operator-install
    apiGroup: policy.open-cluster-management.io
    kind: Policy
