# This policy configures the noobaa backing store if using the default storage class
# in your cluster. When in AWS, this is not needed if AWS s3 will be used.
#
# Note that OpenShift 4.18 is required.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-noobaa-backing-store
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: AutoShiftv2
    policy.open-cluster-management.io/categories: OpenShift Data Foundation
    policy.open-cluster-management.io/controls: OpenShift Standard
spec:
  dependencies:
    - name: policy-storage-cluster
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: noobaa-backing-store
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: noobaa.io/v1alpha1
                kind: BackingStore
                metadata:
                  name: noobaa-default-backing-store
                  namespace: {{ .Values.odf.namespace }}
                spec:
                  pvPool:
                    numVolumes: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/odf-nooba-store-size" | default "{{ .Values.odf.noobaStoreNumVolumes }}" hub{{ "}}" }}'
                    resources:
                      limits:
                        cpu: 1000m
                        memory: 4000Mi
                      requests:
                        cpu: 500m
                        memory: 500Mi
                        storage: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/odf-nooba-store-num-volumes" | default "{{ .Values.odf.noobaStoreSize }}" hub{{ "}}" }}'
                    secret: {}
                  type: pv-pool
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-noobaa-backing-store
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/odf-nooba-pvpool'
              operator: In
              values:
              - 'true'
            - key: 'autoshift.io/odf'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-noobaa-backing-store
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-noobaa-backing-store
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-noobaa-backing-store
    apiGroup: policy.open-cluster-management.io
    kind: Policy
