# Default values for commvault-backup
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: policy-cluster-installs
commvault:
  saname: commvault-sa
  namespace: commvault




### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# commvault-backup<bool>: 'true' or 'false' - Controls whether commvault-backup is managed

# Examples:
# autoshift.io/commvault-backup: 'true'

