# This policy installs the Advanced Cluster Security Operator on the ACM hub
# cluster and creates the Central Server.
{{- if .Values.hubClusterSets }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-acs-central
  namespace: {{ .Values.policy_namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "1"
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management, CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration, CA-2 Security Assessments
spec:
{{ if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{ end }}
  disabled: false
  dependencies:
    - name: policy-acs-operator-install
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acs-central
        spec:
          remediationAction: enforce
          severity: high
          evaluationInterval:
            compliant: {{ ((($.Values.autoshift).evaluationInterval).compliant) | default "10m" }}
            noncompliant: {{ ((($.Values.autoshift).evaluationInterval).noncompliant) | default "30s" }}
          object-templates-raw: |
            - complianceType: musthave
              objectDefinition:
                apiVersion: platform.stackrox.io/v1alpha1
                kind: Central
                metadata:
                  namespace: {{ .Values.acs.namespace }}
                  name: stackrox-central-services
                spec:
                  central:
                    exposure:
                      loadBalancer:
                        enabled: false
                        port: 443
                      nodePort:
                        enabled: false
                      route:
                        enabled: true
                    persistence:
                      persistentVolumeClaim:
                        claimName: stackrox-db
                  egress:
                    connectivityPolicy: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/acs-egress-connectivity" | default "{{ .Values.acs.egressConnectivity }}" {{ "hub}}" }}'
                  scanner:
                    analyzer:
                      scaling:
                        autoScaling: Enabled
                        maxReplicas: 5
                        minReplicas: 2
                        replicas: 3
                    scannerComponent: Enabled
                  scannerV4:
                    scannerComponent: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/acs-scanner-v4" | default "{{ .Values.acs.scannerV4 }}" {{ "hub}}" }}'
                  {{ "{{hub-" }} if eq (index .ManagedClusterLabels "autoshift.io/acs-monitoring" | default "{{ .Values.acs.monitoring }}") "true" {{ "hub}}" }}
                  monitoring:
                    openshift:
                      enabled: true
                  {{ "{{hub-" }} end {{ "hub}}" }}
                  {{ "{{hub-" }} if (index .ManagedClusterLabels "autoshift.io/acs-network-policies") {{ "hub}}" }}
                  network:
                    policies: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/acs-network-policies" {{ "hub}}" }}'
                  {{ "{{hub-" }} end {{ "hub}}" }}
                  {{ "{{hub-" }} if eq (index .ManagedClusterLabels "autoshift.io/acs-vm-scanning" | default "") "true" {{ "hub}}" }}
                  customize:
                    envVars:
                      - name: ROX_VIRTUAL_MACHINES
                        value: "true"
                  {{ "{{hub-" }} end {{ "hub}}" }}
            {{ "{{hub-" }} if (index .ManagedClusterLabels "autoshift.io/acs-auth-provider") {{ "hub}}" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: platform.stackrox.io/v1alpha1
                kind: Central
                metadata:
                  namespace: {{ .Values.acs.namespace }}
                  name: stackrox-central-services
                spec:
                  central:
                    declarativeConfiguration:
                      configMaps:
                        - name: acs-declarative-configs
            {{ "{{hub-" }} end {{ "hub}}" }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: acs-central-test
        spec:
          remediationAction: inform
          severity: high
          evaluationInterval:
            compliant: {{ ((($.Values.autoshift).evaluationInterval).compliant) | default "10m" }}
            noncompliant: {{ ((($.Values.autoshift).evaluationInterval).noncompliant) | default "30s" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: platform.stackrox.io/v1alpha1
                kind: Central
                metadata:
                  namespace: {{ .Values.acs.namespace }}
                  name: stackrox-central-services
                status:
                  conditions:
                    - status: 'True'
                      type: Deployed
                    - status: 'True'
                      type: Initialized
                    - status: 'False'
                      type: ReleaseFailed
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policy-acs-central-placement
  namespace: {{ .Values.policy_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/acs'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-acs-central-placement
  namespace: {{ .Values.policy_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
placementRef:
  name: policy-acs-central-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-acs-central
    apiGroup: policy.open-cluster-management.io
    kind: Policy
{{- end -}}