kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: netapp-nvme-rwx
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
    storageclass.kubevert.io/is-default-virt-class: 'true'
provisioner: csi.trident.netapp.io
parameters:
  fsType: ext4
  storagePools: 'optix-nvme-backend:.*'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
