apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  annotations: 
    snapshot.storage.kubernetes.io/is-default-class: "true"
  name: trident-csi-snapclass
driver: csi.trident.netapp.io
deletionPolicy: Delete
