apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: optix-nvme-backend
  namespace: trident
spec:
  backendName: optix-nvme-backend
  credentials:
    name: backend-tbc-ontap-san-secret
  managementLIF: 10.84.37.130
  sanType: nvme
  storageDriverName: ontap-san
  useREST: true
  version: 1
