# placement-storage-pvc.yaml restricts this to pvc-backed clusters, so no storage-type
# conditional belongs here.
object-templates-raw: |
  - complianceType: musthave
    objectDefinition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: image-registry-storage
        namespace: openshift-image-registry
      spec:
        accessModes:
          - {{hub index .ManagedClusterLabels "autoshift.io/imageregistry-pvc-access-mode" hub}}
        resources:
          requests:
            storage: {{hub index .ManagedClusterLabels "autoshift.io/imageregistry-pvc-size" | default "100Gi" hub}}
        volumeMode: {{hub index .ManagedClusterLabels "autoshift.io/imageregistry-pvc-volume-mode" | default "Filesystem" hub}}
        storageClassName: {{hub index .ManagedClusterLabels "autoshift.io/imageregistry-pvc-storage-class" hub}}
