# Default values for oauth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
auth_remove_kubeadmin: false
oauth: 'false'
auth_secrets_namespace: "cluster-install-secrets"

# LDAP options
ldap_job_image: quay.io/openshift/origin-cli:latest
ldap_groupsync_namespace: ldap-sync
ldap_groupsync_secret: ldap-secret
ldap_schedule: "*/90 * * * *"
ldap_successfulJobsHistoryLimit: 5
ldap_failedJobsHistoryLimit: 3

#Entra ID 
entra_id_secret: entraid-client-secret
# RoleBindings
# rolebindings:
#   - subject: Group, User, or ServiceAccount name
#     subject-namespace: ServiceAccount namespace
#     namespace: If the RoleBinding will be scoped to a single Namespace
#     kind: Group, User, or ServiceAccount
#     role: Name of the Role to bind
#     cluster-role: Name of the ClusterRole to bind

# Labels
# autoshift.io/oauth<bool>: If not set the Oauth will not be managed. default false
# autoshift.io/oauth-remove-kubeadmin: If set to true, the kubeadmin user will be removed
# autoshift.io/oauth-config-file<string>: Filename of Oauth Identity Provider config in files/oauth to apply to clusters
# autoshift.io/rolebindings-config-file<string>: Filename of Rolebindings in files/rolebindings to apply to clusters
# autoshift.io/ldap-sync-config-file<string>: Filename of LDAP sync config files in files/ldap-sync to apply to clusters
# autoshift.io/ldap-groupsync-secret<string>: Name of secret on cluster that contains the service account password. Gets mounted at `/etc/ldap/password` if specified
