---
policy_namespace: open-cluster-policies
gitopsNamespace: openshift-gitops

namespace: "kva-informer"
acceptEula: "Y"

kvaHubSecretNamespace: cluster-install-secrets

kvaInformer:
  releaseName: "servicenow-kva-informer"
  helmURL: "https://install.service-now.com/glide/distribution/builds/package/informer/informer-helm/repo"
  appVersion: "2.7.1"

servicenow:
  instance:
    name: "vasubprod1"
    domain: "servicenowservices.com"

customRootCA:
  use: true

kubevirt:
  enabled: true
...
