{{- $policyName := "policy-rhoai-operator-install" }}
{{- $placementName := "placement-policy-rhoai-operator-install" }}

apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $policyName }}
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhoai-operator-ns
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ .Values.rhoai.namespace }}
                  labels:
                    openshift.io/cluster-monitoring: "true"
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-rhoai
        spec:
          remediationAction: enforce
          severity: high
          complianceType: musthave
          operatorGroup:
            name: {{ .Values.rhoai.operatorGroupName }}
            namespace: {{ .Values.rhoai.namespace }}
            {{- if .Values.rhoai.targetNamespaces }}
            targetNamespaces:
              {{- range .Values.rhoai.targetNamespaces }}
              - {{ . }}
              {{- end }}
            {{- end }}
          subscription:
            startingCSV: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/rhoai-version" | default "" {{ "hub}}" }}'
            namespace: {{ .Values.rhoai.namespace }}
            channel: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/rhoai-channel" | default "{{ .Values.rhoai.channel }}" {{ "hub}}" }}'
            name: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/rhoai-subscription-name" | default "{{ .Values.rhoai.name }}" {{ "hub}}" }}'
            source: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/rhoai-source" | default "{{ .Values.rhoai.source }}" {{ "hub}}" }}'
            sourceNamespace: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/rhoai-source-namespace" | default "{{ .Values.rhoai.sourceNamespace }}" {{ "hub}}" }}'
          # Upgrade approval for subscription will be set based on if version is set not this flag
          # If version is set install plan is set to manual and only the version specified will be installed
          upgradeApproval: Automatic
          versions:
            - '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/rhoai-version" | default "" {{ "hub}}" }}'
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ $placementName }}
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/rhoai'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ $placementName }}
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: {{ $placementName }}
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: {{ $policyName }}
    apiGroup: policy.open-cluster-management.io
    kind: Policy