version: 2
updates:
  - package-ecosystem: gomod
    directory: /tools
    schedule:
      interval: weekly
    reviewers:
      - bcarr-rh
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - bcarr-rh
    labels:
      - dependencies
