---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: localhost
    managed: false
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: "${MOLECULE_PROJECT_DIRECTORY}/.."
  inventory:
    host_vars:
      localhost:
        ansible_connection: local
verifier:
  name: ansible
