apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: storage-net
  namespace: openshift-storage
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "enp6s19",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.55.128/25"
        }
    }'