apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: acs-central
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates-raw: |
    - complianceType: musthave
      objectDefinition:
        apiVersion: platform.stackrox.io/v1alpha1
        kind: Central
        metadata:
          namespace: stackrox
          name: stackrox-central-services
        spec:
          central:
            exposure:
              loadBalancer:
                enabled: false
                port: 443
              nodePort:
                enabled: false
              route:
                enabled: true
            persistence:
              persistentVolumeClaim:
                claimName: stackrox-db
            {{hub- if (index .ManagedClusterLabels "autoshift.io/acs-auth-provider") hub}}
            declarativeConfiguration:
              configMaps:
                - name: acs-declarative-configs
            {{hub- end hub}}
          egress:
            connectivityPolicy: '{{hub index .ManagedClusterLabels "autoshift.io/acs-egress-connectivity" | default "Online" hub}}'
          scanner:
            analyzer:
              scaling:
                autoScaling: Enabled
                maxReplicas: 5
                minReplicas: 2
                replicas: 3
            scannerComponent: Enabled
          scannerV4:
            scannerComponent: '{{hub index .ManagedClusterLabels "autoshift.io/acs-scanner-v4" | default "Enabled" hub}}'
          {{hub- if eq (index .ManagedClusterLabels "autoshift.io/acs-monitoring" | default "true") "true" hub}}
          monitoring:
            openshift:
              enabled: true
          {{hub- end hub}}
          {{hub- if (index .ManagedClusterLabels "autoshift.io/acs-network-policies") hub}}
          network:
            policies: '{{hub index .ManagedClusterLabels "autoshift.io/acs-network-policies" hub}}'
          {{hub- end hub}}
          {{hub- if eq (index .ManagedClusterLabels "autoshift.io/acs-vm-scanning" | default "") "true" hub}}
          customize:
            envVars:
              - name: ROX_VIRTUAL_MACHINES
                value: "true"
          {{hub- end hub}}
