apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: acs-declarative-config
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates-raw: |
    {{hub- if (index .ManagedClusterLabels "autoshift.io/acs-auth-provider") hub}}
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: acs-declarative-configs
          namespace: stackrox
        data:
          auth-provider.yaml: |
            name: OpenShift
            minimumRole: '{{hub index .ManagedClusterLabels "autoshift.io/acs-auth-min-role" | default "None" hub}}'
            openshift:
              enable: true
            groups:
              - key: groups
                value: '{{hub index .ManagedClusterLabels "autoshift.io/acs-auth-admin-group" | default "cluster-admins" hub}}'
                role: Admin
    {{hub- end hub}}
