apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: compliance-suite-stig-test
spec:
  remediationAction: inform
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates:
    - complianceType: musthave # this template checks if scan has completed by checking the status field
      objectDefinition:
        apiVersion: compliance.openshift.io/v1alpha1
        kind: ComplianceSuite
        metadata:
          name: stig
          namespace: openshift-compliance
        status:
          phase: DONE
