apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: acm-addon-governance-framework-ref
spec:
  remediationAction: ${REMEDIATION}
  severity: medium
  evaluationInterval:
    compliant: ${EVAL_COMPLIANT}
    noncompliant: ${EVAL_NONCOMPLIANT}
  object-templates:
  - complianceType: musthave
    recreateOption: IfRequired
    objectDefinition:
      apiVersion: addon.open-cluster-management.io/v1alpha1
      kind: ClusterManagementAddOn
      metadata:
        name: governance-policy-framework
      spec:
        supportedConfigs:
        - group: addon.open-cluster-management.io
          resource: addondeploymentconfigs
          defaultConfig:
            name: governance-policy-framework-tuning
            namespace: open-cluster-management
