apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: jfrog-scc
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: security.openshift.io/v1
        kind: SecurityContextConstraints
        metadata:
          name: anyuid
        users:
          - system:serviceaccount:openshift-operators:artifactory-ha-operator
          - system:serviceaccount:jfrog-system:openshiftartifactoryha-artifactory-ha
