object-templates-raw: |
  - complianceType: musthave
    objectDefinition:
      apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      metadata:
        name: version
      spec:
        channel: '{{hub index .ManagedClusterLabels "autoshift.io/openshift-upgrade-channel" | default "stable-4.20" hub}}'
        desiredUpdate:
          version: '{{hub index .ManagedClusterLabels "autoshift.io/openshift-upgrade-version" hub}}'
