# Service Mesh 3 Operator
# Portable Helm chart - works with or without ACM
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.servicemesh3.name }}
  namespace: {{ .Values.servicemesh3.namespace }}
spec:
  channel: {{ .Values.servicemesh3.channel }}
  name: {{ .Values.servicemesh3.name }}
  source: {{ .Values.servicemesh3.source }}
  sourceNamespace: {{ .Values.servicemesh3.sourceNamespace }}
