apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: openshift-coo-uiplugin-logging
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: observability.openshift.io/v1alpha1
        kind: UIPlugin
        metadata:
          name: logging
        spec:
          logging:
            lokiStack:
              name: '{{hub index .ManagedClusterLabels "autoshift.io/loki-lokistack-name" | default "logging-lokistack" hub}}'
          type: Logging
