{{ $policyNamespace := $.Values.policy_namespace }}
apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: "managed-autoshift"
  namespace: {{ $policyNamespace }}
spec:
  description:  "This policy set manages autoshift installation on hub clusters"
  policies:
    - "policy-managed-autoshift-repo"
    - "policy-managed-autoshift-ns"
    - "policy-managed-autoshift"


