{{ $policyName := "policy-infra-gitops"  }}
{{ $configPolicyName := "create-infra-gitops" }}
{{ $placementName := printf "placement-%s" $policyName }}
{{ $labelPrefix := .Values.infraNodes.labelPrefix | default "autoshift.io/" }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $policyName }}
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/categories: OpenShift GitOps
    policy.open-cluster-management.io/controls: OpenShift Standard
    policy.open-cluster-management.io/standards: AutoShiftv2
spec:
  disabled: {{ not .Values.infraNodes.gitops.migrate }}
  remediationAction: {{ .Values.infraNodes.gitops.remediationAction | default "enforce" }}
  dependencies:
  {{- range .Values.infraNodes.dependencies.install }}
  - apiVersion: policy.open-cluster-management.io/v1
    compliance: Compliant
    kind: Policy
    name: {{ . }}
    namespace: {{ $.Values.policy_namespace }}
  {{- end }}
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ $configPolicyName }}
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: {{ .Values.infraNodes.gitops.apiVersion }}
                kind: {{ .Values.infraNodes.gitops.kind }}
                metadata:
                  name: {{ .Values.infraNodes.gitops.metadata.name }}
                  namespace: {{ .Values.infraNodes.gitops.namespace }}
                spec:
                  runOnInfra: true
                  tolerations:
                    - effect: NoSchedule
                      key: node-role.kubernetes.io/infra
                    - effect: NoExecute
                      key: node-role.kubernetes.io/infra
          remediationAction: inform
          severity: high
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ $placementName }}
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: {{ printf "%s%s" $labelPrefix "infra-nodes" }}
              operator: Exists
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ $placementName }}
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: {{ $placementName }}
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: {{ $policyName }}
    apiGroup: policy.open-cluster-management.io
    kind: Policy
