# Network Operator — configure OVN-Kubernetes for ambient mode
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: servicemesh3-ambient-network-operator
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: operator.openshift.io/v1
        kind: Network
        metadata:
          name: cluster
        spec:
          defaultNetwork:
            ovnKubernetesConfig:
              gatewayConfig:
                routingViaHost: true
