apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: servicemesh3-ambient-tempo-bucket
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: objectbucket.io/v1alpha1
        kind: ObjectBucketClaim
        metadata:
          name: tempo-bucket-odf
          namespace: tracing-system
        spec:
          generateBucketName: tempo-bucket-odf
          storageClassName: openshift-storage.noobaa.io
