apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: servicemesh3-ambient-tempo-ca-bundle
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: tempo-s3-ca-bundle
          namespace: tracing-system
          annotations:
            service.beta.openshift.io/inject-cabundle: "true"
