{{- $policyNamespace := $.Values.policy_namespace }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-openshift-version
  namespace: {{ $policyNamespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-version-check
        spec:
          remediationAction: inform
          severity: high
          evaluationInterval:
            compliant: {{ ((($.Values.autoshift).evaluationInterval).compliant) | default "10m" }}
            noncompliant: {{ ((($.Values.autoshift).evaluationInterval).noncompliant) | default "30s" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterVersion
                metadata:
                  name: version
                spec:
                  desiredUpdate:
                    version: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/openshift-version" | default "" {{ "hub}}" }}'
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-openshift-version
  namespace: {{ $policyNamespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-openshift-version
  namespace: {{ $policyNamespace }}
placementRef:
  name: placement-policy-openshift-version
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-openshift-version
    apiGroup: policy.open-cluster-management.io
    kind: Policy
