apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-metallb-operator-install
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: metallb-operator-ns
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ .Values.metallb.namespace }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-operator-metallb
        spec:
          remediationAction: enforce
          severity: high
          complianceType: musthave
          operatorGroup:
            name: {{ .Values.metallb.name }}
            namespace: {{ .Values.metallb.namespace }}
          subscription:
            namespace: {{ .Values.metallb.namespace }}
            channel: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/metallb-channel" | default "{{ .Values.metallb.channel }}" hub{{ "}}" }}'
            name: {{ .Values.metallb.name }}
            source: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/metallb-source" | default "{{ .Values.metallb.source }}" hub{{ "}}" }}'
            sourceNamespace: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/metallb-source-namespace" | default "{{ .Values.metallb.sourceNamespace }}" hub{{ "}}" }}'
          # Getting Label and then capitalizing first letter
          upgradeApproval: '{{ "{{hub" }} $upgrade_approval := index .ManagedClusterLabels "autoshift.io/metallb-install-plan-approval" | default "{{ .Values.metallb.installPlanApproval }}" {{ "-hub}}" }} {{ "{{hub" }} print (substr 0 1 $upgrade_approval | upper) (substr 1 (len $upgrade_approval) $upgrade_approval) {{ "-hub}}" }}'
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-metallb-csv-check
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: ClusterServiceVersion
                metadata:
                  namespace: {{ .Values.metallb.namespace }}
                status:
                  phase: Succeeded
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-metallb-operator-install
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/metallb'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-metallb-operator-install
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-metallb-operator-install
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-metallb-operator-install
    apiGroup: policy.open-cluster-management.io
    kind: Policy
