apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-metallb-operator-install
  namespace: {{ .Values.policy_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-metallb-namespace
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ .Values.metallb.namespace }}

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: deploy-operator-group
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: "{{ .Values.metallb.name }}"
                  namespace: "{{ .Values.metallb.namespace }}"
                spec: {}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: deploy-subscription
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: {{ .Values.metallb.namespace }}
                  namespace: {{ .Values.metallb.namespace }}
                spec:
                  channel: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/metallb-channel" | default "{{ .Values.metallb.channel }}" hub{{ "}}" }}'
                  name: {{ .Values.metallb.name }}
                  source: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/metallb-source" | default "{{ .Values.metallb.source }}" hub{{ "}}" }}'
                  sourceNamespace: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/metallb-source-namespace" | default "{{ .Values.metallb.sourceNamespace }}" hub{{ "}}" }}'
                  installPlanApproval: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/metallb-install-plan-approval" | default "{{ .Values.metallb.installPlanApproval }}" hub{{ "}}" }}'

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-metallb-csv-check
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: ClusterServiceVersion
                metadata:
                  namespace: {{ .Values.metallb.namespace }}
                status:
                  phase: Succeeded
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-metallb-operator-install
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/metallb'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-metallb-operator-install
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-metallb-operator-install
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-metallb-operator-install
    apiGroup: policy.open-cluster-management.io
    kind: Policy
