---
# Default values for rh-acm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
aap-ocp-virt: false
virt_ns: aap-ocp-virt
oc_cli_image: quay.io/openshift/origin-cli:latest
virt_token_cron_schedule: "0 0 1 * *"
virt_token_expiry_days: 365
virt_token_renewal_threshold_days: 35
