apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: acm-observability-ns
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: ${EVAL_COMPLIANT}
    noncompliant: ${EVAL_NONCOMPLIANT}
  object-templates:
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: open-cluster-management-observability
        labels:
          openshift.io/cluster-monitoring: 'true'
