apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: acm-observability-bucket
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: ${EVAL_COMPLIANT}
    noncompliant: ${EVAL_NONCOMPLIANT}
  object-templates:
  - complianceType: musthave
    objectDefinition:
      apiVersion: objectbucket.io/v1alpha1
      kind: ObjectBucketClaim
      metadata:
        name: acm-observability
        namespace: open-cluster-management-observability
      spec:
        storageClassName: openshift-storage.noobaa.io
        generateBucketName: acm-observability
