{{- $policyName := "managed-hub-autoshift" }}
{{- $policyNamespace := $.Values.policy_namespace }}
{{- $placementName := printf "%s-%s" "placement" $policyName }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoshift-repo-urls
  namespace: {{ $policyNamespace }}
data: |
{{- range $clusterSetName, $clusterSet := $.Values.hubClusterSets }}
  {{ $clusterSet | toRawJson }}
  {{- $repoUrl := (index $clusterSet "autoshiftReopUrl" | default $.Values.autoshiftGitRepo | default "all-values-failed") }}
  {{- if ne $repoUrl "" }}
    {{ $clusterSetName }}: {{ $repoUrl }}
  {{- end }}
{{- end }}

