apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-create-idp-serviceaccount
  namespace: {{ .Values.policy_namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "1"
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    {{- if not .Values.ignoreHelmHooks }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-idp-patch-service-account
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            # Create namespace exists
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ .Values.namespace }}
            # Create Service Account 
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ServiceAccount
                metadata:
                  name: {{ .Values.namespace }}-patch-sa
                  namespace: {{ .Values.namespace }}
            # ClusterRole with least privilege
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRole
                metadata:
                  name: {{ .Values.namespace }}-oauth-patcher
                rules:
                - apiGroups: ["config.openshift.io"]
                  resources: ["oauths"]
                  verbs: ["get","patch","update"]
            # Create Rolebinding 
            - complianceType: musthave
              pruneObjectBehavior: DeleteIfCreated
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: {{ .Values.namespace }}-oauth-patcher-binding
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: {{ .Values.namespace }}-oauth-patcher
                subjects:
                  - kind: ServiceAccount
                    name: {{ .Values.namespace }}-patch-sa
                    namespace: {{ .Values.namespace }}

            # Allow writing the health CM in the target ns
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: {{ .Values.namespace }}-cm-writer
                  namespace: {{ .Values.namespace }}
                rules:
                - apiGroups: [""]
                  resources: ["configmaps"]
                  verbs: ["get","create","update","patch"]
            #  Update service account
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: {{ .Values.namespace }}-cm-writer-binding
                  namespace: {{ .Values.namespace }}
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: Role
                  name: {{ .Values.namespace }}-cm-writer
                subjects:
                - kind: ServiceAccount
                  name: {{ .Values.namespace }}-patch-sa
                  namespace: {{ .Values.namespace }}


    {{- end }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-create-idp-serviceaccount
  namespace: {{ .Values.policy_namespace }}

spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}

  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/rhbk-idp'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placementbinding-policy-create-idp-serviceaccount
  namespace: {{ .Values.policy_namespace }}
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-policy-create-idp-serviceaccount
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-create-idp-serviceaccount

