apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-gitops-dev-standalone
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
{{ if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{ end }}
  disabled: false
  dependencies:
    - name: policy-gitops-operator-install
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: gitops-dev-standalone
        spec:
          remediationAction: enforce
          severity: high
          evaluationInterval:
            compliant: {{ ((($.Values.autoshift).evaluationInterval).compliant) | default "10m" }}
            noncompliant: {{ ((($.Values.autoshift).evaluationInterval).noncompliant) | default "30s" }}
          object-templates-raw: |
            {{ "{{hub-" }} $cm := (lookup "v1" "ConfigMap" "{{ $.Values.policy_namespace }}" (printf "%s.rendered-config" .ManagedClusterName)) | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $configData := (index $cm "data" | default dict) {{ "hub}}" }}
            {{ "{{hub-" }} $configYaml := (index $configData "config" | default "" | fromYaml | default dict) {{ "hub}}" }}
            {{ "{{hub-" }} $devConfig := (index $configYaml "gitops-dev" | default dict) {{ "hub}}" }}
            {{ "{{hub-" }} range $label, $val := .ManagedClusterLabels {{ "hub}}" }}
            {{ "{{hub-" }} if and (hasPrefix "autoshift.io/gitops-dev-team-" $label) (not (hasSuffix "-tssc" $label)) {{ "hub}}" }}
            {{ "{{hub-" }} if eq $val "standalone" {{ "hub}}" }}
            {{ "{{hub-" }} $team := replace "autoshift.io/gitops-dev-team-" "" $label {{ "hub}}" }}
            {{ "{{hub-" }} $tc := index $devConfig $team | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $rbacList := index $tc "rbac_policies" | default list {{ "hub}}" }}
            {{ "{{hub-" }} $policies := prepend $rbacList "g, system:cluster-admins, role:admin" {{ "hub}}" }}
            {{ "{{hub-" }} $serverLimits := index (index $tc "server" | default dict) "limits" | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $serverReqs := index (index $tc "server" | default dict) "requests" | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $dexLimits := index (index $tc "dex" | default dict) "limits" | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $dexReqs := index (index $tc "dex" | default dict) "requests" | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $repoLimits := index (index $tc "repo" | default dict) "limits" | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $repoReqs := index (index $tc "repo" | default dict) "requests" | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $haConf := index $tc "ha" | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $haLimits := index $haConf "limits" | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $haReqs := index $haConf "requests" | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $redisLimits := index (index $tc "redis" | default dict) "limits" | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $redisReqs := index (index $tc "redis" | default dict) "requests" | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $ctrlLimits := index (index $tc "controller" | default dict) "limits" | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $ctrlReqs := index (index $tc "controller" | default dict) "requests" | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $appSetLimits := index (index $tc "applicationSet" | default dict) "limits" | default dict {{ "hub}}" }}
            {{ "{{hub-" }} $appSetReqs := index (index $tc "applicationSet" | default dict) "requests" | default dict {{ "hub}}" }}
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: openshift-gitops-{{ "{{hub" }} $team {{ "hub}}" }}
                  labels:
                    openshift.io/cluster-monitoring: "true"
            - complianceType: musthave
              objectDefinition:
                apiVersion: argoproj.io/v1beta1
                kind: ArgoCD
                metadata:
                  name: argocd-dev
                  namespace: openshift-gitops-{{ "{{hub" }} $team {{ "hub}}" }}
                spec:
                  server:
                    resources:
                      limits:
                        cpu: {{ "{{hub" }} index $serverLimits "cpu" | default "500m" {{ "hub}}" }}
                        memory: {{ "{{hub" }} index $serverLimits "memory" | default "256Mi" {{ "hub}}" }}
                      requests:
                        cpu: {{ "{{hub" }} index $serverReqs "cpu" | default "125m" {{ "hub}}" }}
                        memory: {{ "{{hub" }} index $serverReqs "memory" | default "128Mi" {{ "hub}}" }}
                    route:
                      enabled: true
                  monitoring:
                    enabled: false
                  sso:
                    dex:
                      resources:
                        limits:
                          cpu: {{ "{{hub" }} index $dexLimits "cpu" | default "500m" {{ "hub}}" }}
                          memory: {{ "{{hub" }} index $dexLimits "memory" | default "256Mi" {{ "hub}}" }}
                        requests:
                          cpu: {{ "{{hub" }} index $dexReqs "cpu" | default "125m" {{ "hub}}" }}
                          memory: {{ "{{hub" }} index $dexReqs "memory" | default "128Mi" {{ "hub}}" }}
                      openShiftOAuth: true
                    provider: dex
                  rbac:
                    defaultPolicy: ''
                    policy: |
                      {{ "{{hub" }} join "\n                      " $policies {{ "hub}}" }}
                    scopes: '[groups]'
                  repo:
                    resources:
                      limits:
                        cpu: {{ "{{hub" }} index $repoLimits "cpu" | default "1000m" {{ "hub}}" }}
                        memory: {{ "{{hub" }} index $repoLimits "memory" | default "1024Mi" {{ "hub}}" }}
                      requests:
                        cpu: {{ "{{hub" }} index $repoReqs "cpu" | default "250m" {{ "hub}}" }}
                        memory: {{ "{{hub" }} index $repoReqs "memory" | default "256Mi" {{ "hub}}" }}
                  ha:
                    resources:
                      limits:
                        cpu: {{ "{{hub" }} index $haLimits "cpu" | default "500m" {{ "hub}}" }}
                        memory: {{ "{{hub" }} index $haLimits "memory" | default "256Mi" {{ "hub}}" }}
                      requests:
                        cpu: {{ "{{hub" }} index $haReqs "cpu" | default "125m" {{ "hub}}" }}
                        memory: {{ "{{hub" }} index $haReqs "memory" | default "128Mi" {{ "hub}}" }}
                    enabled: {{ "{{hub" }} index $haConf "enabled" | default "false" {{ "hub}}" }}
                  redis:
                    resources:
                      limits:
                        cpu: {{ "{{hub" }} index $redisLimits "cpu" | default "500m" {{ "hub}}" }}
                        memory: {{ "{{hub" }} index $redisLimits "memory" | default "256Mi" {{ "hub}}" }}
                      requests:
                        cpu: {{ "{{hub" }} index $redisReqs "cpu" | default "125m" {{ "hub}}" }}
                        memory: {{ "{{hub" }} index $redisReqs "memory" | default "128Mi" {{ "hub}}" }}
                  controller:
                    resources:
                      limits:
                        cpu: {{ "{{hub" }} index $ctrlLimits "cpu" | default "2000m" {{ "hub}}" }}
                        memory: {{ "{{hub" }} index $ctrlLimits "memory" | default "2048Mi" {{ "hub}}" }}
                      requests:
                        cpu: {{ "{{hub" }} index $ctrlReqs "cpu" | default "250m" {{ "hub}}" }}
                        memory: {{ "{{hub" }} index $ctrlReqs "memory" | default "1024Mi" {{ "hub}}" }}
                  applicationSet:
                    resources:
                      limits:
                        cpu: {{ "{{hub" }} index $appSetLimits "cpu" | default "2" {{ "hub}}" }}
                        memory: {{ "{{hub" }} index $appSetLimits "memory" | default "1Gi" {{ "hub}}" }}
                      requests:
                        cpu: {{ "{{hub" }} index $appSetReqs "cpu" | default "250m" {{ "hub}}" }}
                        memory: {{ "{{hub" }} index $appSetReqs "memory" | default "512Mi" {{ "hub}}" }}
                  resourceExclusions: |
                    - apiGroups:
                      - tekton.dev
                      clusters:
                      - '*'
                      kinds:
                      - TaskRun
                      - PipelineRun
                  disableAdmin: '{{ "{{hub" }} index $tc "disableAdmin" | default "true" | toBool {{ "hub}}" }}'
            - complianceType: musthave
              objectDefinition:
                apiVersion: argoproj.io/v1alpha1
                kind: RolloutManager
                metadata:
                  name: argo-rollout
                  namespace: openshift-gitops-{{ "{{hub" }} $team {{ "hub}}" }}
                  labels:
                    example: basic
            {{ "{{hub-" }} end {{ "hub}}" }}
            {{ "{{hub-" }} end {{ "hub}}" }}
            {{ "{{hub-" }} end {{ "hub}}" }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-gitops-dev-standalone
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/gitops-dev'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-gitops-dev-standalone
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-gitops-dev-standalone
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-gitops-dev-standalone
    apiGroup: policy.open-cluster-management.io
    kind: Policy
