{{- $managedHubs := dict }}
{{- $selfManagedHubs := dict }}
{{- range $k, $v := $.Values.hubClusterSets  }}
  {{-  if eq ((index $v.labels "self-managed") | default "true")  "false" }}
    {{- $_ := set $managedHubs $k $k }}
  {{- else }}
    {{- $_ := set $selfManagedHubs $k $k }}
  {{- end }}
{{- end }}
{{- $policyNamespace := $.Values.policy_namespace }}
{{- range $_, $target := (list "hubofhubs" "managedHub") }}
  {{- /* Skip managedHub target if there are no managed hubs */ -}}
 {{- if and (eq $target "managedHub") (empty $managedHubs) }}
    {{- continue }}
  {{- end }}
  {{- $policyName := (printf "policy-%s-labels" ($target | lower)) }}
  {{- $configPolicyName := printf "configure-%s" $policyName }}
  {{- $placementName := printf "placement-%s" $policyName }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $policyName }}
  namespace: {{ $policyNamespace }}
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
    {{- if and (eq $target "managedHub") (not (empty $managedHubs)) }}
  dependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
      name:  "policy-managed-hub-namespace"
      namespace: {{ $policyNamespace }}
    {{- end }}
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ $configPolicyName }}
        spec:
          severity: high
          object-templates-raw: |
            [
              {{ if eq $target "managedHub" }}
              {{ "{{hub" }} $policyNamespace = (index .ManagedClusterLabels "{{ $.Values.autoshiftLabelPrefix | default "autoshift.io/" }}autoshift-policy-namespace") | default  (index .ManagedClusterLabels "{{ $.Values.autoshiftLabelPrefix | default "autoshift.io/" }}policy-namespace") | default (printf "%s-%s" "policies" .ManagedClusterName) {{ "hub}}" }}
              {{ "{{-" }} $policyNamespace := "{{ "{{hub" }} $policyNamespace  {{ "hub}}" }}" {{ "}}" }}
              {{ else }}
              {{ "{{-" }} $policyNamespace := "{{ $.Values.policy_namespace }}" {{ "}}" }}
              {{ end }}
              {{ "{{-" }} $managedClusterLookupResult := (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "") | default dict {{ "}}" }}
              {{ "{{-" }} if not (empty $managedClusterLookupResult) {{ "}}" }}
                {{ "{{-" }} $managedClusters := (index $managedClusterLookupResult "items") | default list {{ "}}" }}
                {{ "{{-" }} $lastIndex := (sub (len $managedClusters) 1) {{ "}}" }}
                {{ "{{-" }} if (ne $lastIndex -1) {{ "}}" }}
                  {{ "{{-" }} range $index, $cluster := $managedClusters {{ "}}" }}
                    {{ "{{-" }} $existingLabels :=  (index $cluster "metadata" "labels") {{ "}}" }}
                    {{ "{{-" }} $clusterSet := (index $existingLabels "cluster.open-cluster-management.io/clusterset") | default "" {{ "}}" }}
                    {{ "{{-" }} $clusterName := (index $cluster "metadata" "name") {{ "}}" }}
                    {{ "{{-" }} $clusterConfigMap := (lookup "v1" "ConfigMap" $policyNamespace (print "managed-cluster." $clusterName) "autoshift.io/cluster-labels" | default dict) {{ "}}" }}
                    {{ "{{-" }} $clusterSetConfigMap := (lookup "v1" "ConfigMap" $policyNamespace (print "cluster-set." $clusterSet) "autoshift.io/cluster-labels" | default dict) {{ "}}" }}
                    {{ "{{-" }} $clusterData := (index $clusterConfigMap "data" | default dict) {{ "}}" }}
                    {{ "{{-" }} $clusterSetData := (index $clusterSetConfigMap "data" | default dict) {{ "}}" }}
                    {{ "{{-" }} $labelPrefix := (index $clusterData "labelPrefix" | default (index $clusterSetData "labelPrefix" | default "{{ ($.Values.autoshiftLabelPrefix | default "autoshift.io/" ) }}")) {{ "}}" }}
                    {{ "{{-" }} if (ne $clusterSet "") {{ "}}" }}
                    {{ "{{-" }} end {{ "}}" }}
                    {{ "{{-" }} $existingLabelsNoAutoshift := (dict) {{ "}}" }}
                    {{ "{{-" }} range $label, $value := $existingLabels {{ "}}" }}
                      {{ "{{-" }} if not (hasPrefix $labelPrefix $label) {{ "}}" }}
                        {{ "{{-" }} $_ :=  set $existingLabelsNoAutoshift $label $value {{ "}}" }}
                      {{ "{{-" }} end {{ "}}" }}
                    {{ "{{-" }} end {{ "}}" }}
                    {{ "{{-" }} $clusterSetLabels := (index $clusterSetData "labels" | default "") | fromJson | default dict{{ "}}" }}
                    {{ "{{-" }} $clusterLabels := (index $clusterData "labels" | default "") | fromJson | default dict{{ "}}" }}
                    {{ "{{-" }} $tempLabels := merge (dict) $clusterLabels $clusterSetLabels $existingLabelsNoAutoshift {{ "}}" }}
                    {{ "{{-" }} $newLabels := dict {{ "}}" }}
                    {{ "{{-" }} range $label, $value := $tempLabels {{ "}}" }}
                      {{ "{{-" }} if not (and ($label | hasPrefix $labelPrefix) (eq $value "_")) {{ "}}" }}
                        {{ "{{-" }} $_ := set $newLabels $label $value {{ "}}" }}
                      {{ "{{-" }} end {{ "}}" }} {{ "{{-" }} end {{ "}}" }}
                    {{ "{{-" }} $metadata := index $cluster "metadata" {{ "}}" }}
                    {{ "{{-" }} $_ := set $metadata "labels" $newLabels {{ "}}" }}
                    {{ "{{-" }} $objectDefinition := set $cluster "metadata" $metadata {{ "}}" }}
                    {{ "{{-" }} $_ := unset $objectDefinition "status" {{ "}}" }}
                    {
                      "complianceType": "mustonlyhave",
                      "objectDefinition": {{ "{{" }} $objectDefinition | toRawJson  {{ "}}" }}
                    }{{ "{{-" }} if ne $lastIndex $index {{ "}}" }},{{ "{{-" }} end {{ "}}" }}
                  {{ "{{-" }} end {{ "}}" }}
                {{ "{{-" }} end {{ "}}" }}
              {{ "{{-" }} end {{ "}}" }}
            ]
---

  {{- if (eq $target "managedHub") }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ $placementName }}
  namespace: {{ $policyNamespace }}
spec:
  clusterSets:
  {{- range $managedHub, $_ := $managedHubs }}
    - {{ $managedHub }}
  {{- end }}
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
  {{- end }}
  {{- if (eq $target "hubofhubs") }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ $placementName }}
  namespace: {{ $policyNamespace }}
spec:
  clusterSets:
  {{- range $selfManagedHub, $_ := $selfManagedHubs }}
    - {{ $selfManagedHub }}
  {{- end }}
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
  {{- end }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ $placementName }}
  namespace: {{ $policyNamespace }}
placementRef:
  name: {{ $placementName}}
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: {{ $policyName }}
    apiGroup: policy.open-cluster-management.io
    kind: Policy
---
{{- end }}
