# Hub1 - Spoke hub managed by hub-of-hubs
managedClusterSets:
  spokes:
    config: {}
    labels:
      # OpenShift version for cluster deployment and image mirroring
      openshift-version: '4.20.12'
      gitops: 'true' # is expected to be installed on all hub clusters
      gitops-subscription-name: openshift-gitops-operator
      gitops-disable-default-argocd: 'true'
      gitops-channel: gitops-1.19
      gitops-source: redhat-operators
      gitops-source-namespace: openshift-marketplace
      # gitops-namespace: 'openshift-gitops'  # Override ArgoCD namespace per-cluster
      ### infra-nodes
      infra-nodes: ''
      infra-nodes-numcpu: ''
      infra-nodes-memory-mib: ''
      infra-nodes-numcores-per-socket: ''
      infra-nodes-zones: ''
      ### worker-nodes
      worker-nodes: ''
      worker-nodes-numcpu: ''
      worker-nodes-memory-mib: ''
      worker-nodes-numcores-per-socket: ''
      worker-nodes-zones: ''
      ### storage-nodes
      storage-nodes: ''
      storage-nodes-numcpu: ''
      storage-nodes-memory-mib: ''
      storage-nodes-numcores-per-socket: ''
      storage-nodes-zones: ''
      ### OpenShift Data Foundation
      ### Kubernetes NMState Operator
      nmstate: 'false'
      nmstate-subscription-name: kubernetes-nmstate-operator
      # Example nmstate-nncp labels. Label must start with nmstate-nncp
      # also the value must be the name of the config file you want to apply
      # nmstate-nncp-example-bond1: example-bond
      # nmstate-nncp-example-vlan10: example-vlan10
      ### Advanced Cluster Security
      # acs-vm-scanning: 'true'
      # acs-admission-control: 'true'
      # acs-network-policies: Enabled
      # acs-default-policies: 'true'
      ### Developer Spaces
      ### Developer Hub
      ### OpenShift Pipelines
      ### Trusted Artifact Signer
      ### Quay
      ### Developer OpenShift Gitops
      gitops-dev: 'true'
      ### Loki
      ### OpenShift Logging
      ### Cluster Observability Operator
      coo: 'true'
      coo-subscription-name: cluster-observability-operator
      coo-channel: stable
      coo-source: redhat-operators
      coo-source-namespace: openshift-marketplace
      ### Compliance Operator Stig Apply
      ### node-maintenance
      node-maintenance: 'true'
      node-maintenance-subscription-name: node-maintenance-operator
      node-maintenance-channel: stable
      node-maintenance-source: redhat-operators
      node-maintenance-source-namespace: openshift-marketplace
      node-maintenance-version: 'node-maintenance-operator.v5.5.0'
      global-observability: true
