{{- if .Values.disconnectedMirror.catalogs }}
# Policy to configure CatalogSources for mirrored operator catalogs
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-disconnected-catalog-sources
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
{{ if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{ end }}
  disabled: false
  policy-templates:
    {{- range .Values.disconnectedMirror.catalogs }}
    # CatalogSource: {{ .name }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: disconnected-catalog-{{ .name }}
        spec:
          remediationAction: enforce
          severity: high
          evaluationInterval:
            compliant: {{ ((($.Values.autoshift).evaluationInterval).compliant) | default "10m" }}
            noncompliant: {{ ((($.Values.autoshift).evaluationInterval).noncompliant) | default "30s" }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: CatalogSource
                metadata:
                  name: {{ .name }}
                  namespace: openshift-marketplace
                spec:
                  sourceType: grpc
                  image: '{{ "{{hub" }} (index .ManagedClusterLabels "autoshift.io/mirror-registry-host") | default "{{ $.Values.disconnectedMirror.host }}" {{ "hub}}" }}:{{ "{{hub" }} (index .ManagedClusterLabels "autoshift.io/mirror-registry-port") | default "{{ $.Values.disconnectedMirror.port }}" {{ "hub}}" }}{{ "{{hub" }} $path := (index .ManagedClusterLabels "autoshift.io/mirror-registry-path") | default "{{ $.Values.disconnectedMirror.path }}" }}{{ "{{" }} if $path {{ "}}" }}/{{ "{{" }} $path {{ "}}" }}{{ "{{" }} end {{ "hub}}" }}/{{ .imagePath }}:{{ .tag }}'
                  displayName: {{ .displayName | default .name }}
                  publisher: {{ .publisher | default "AutoShift" }}
                  updateStrategy:
                    registryPoll:
                      interval: {{ .updateInterval | default "10m" }}
                  {{- if .priority }}
                  priority: {{ .priority }}
                  {{- end }}
    {{- end }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-disconnected-catalog-sources
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/disconnected-mirror'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-disconnected-catalog-sources
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-disconnected-catalog-sources
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-disconnected-catalog-sources
    apiGroup: policy.open-cluster-management.io
    kind: Policy
{{- end }}
