apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "{{ .Release.Name }}-policies"
  namespace: openshift-gitops
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  {{- if .Values.autoshiftOciRegistry }}
  # OCI Registry mode - deploy from published Helm charts
  # Policy list is dynamically generated during release process
  # DO NOT manually edit this section - it will be overwritten during release
  - list:
      elements:
      # Policy list will be generated here by scripts/release.sh
      # based on actual policies found in policies/ directory
      - name: placeholder-policy
  {{- else }}
  # Git mode - discover policies from Git repository
  - git:
      repoURL: {{ .Values.autoshiftGitRepo }}
      revision: {{ .Values.autoshiftGitBranchTag }}
      directories:
      - path: 'policies/*'
      {{- if .Values.excludePolicies }}
      {{- range .Values.excludePolicies }}
      - path: 'policies/{{ . }}'
        exclude: true
      {{- end }}
      {{- end }}
  {{- end }}
  template:
    metadata:
      {{- if .Values.autoshiftOciRegistry }}
      name: '{{ .Release.Name }}-{{"{{"}} .name {{"}}"}}'
      {{- else }}
      name: '{{ .Release.Name }}-{{"{{"}} .path.basename {{"}}"}}'
      {{- end }}
      labels:
        app: "{{ .Release.Name }}-policies"
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        {{- if .Values.autoshiftOciRegistry }}
        # OCI mode - use Helm chart from registry
        repoURL: {{ .Values.autoshiftOciRegistry }}
        chart: '{{"{{"}} .name {{"}}"}}'
        targetRevision: {{ .Values.autoshiftOciVersion | default .Chart.Version }}
        {{- else }}
        # Git mode - use path in Git repository
        path: '{{"{{"}} .path.path {{"}}"}}'
        repoURL: {{ .Values.autoshiftGitRepo }}
        targetRevision: {{ .Values.autoshiftGitBranchTag }}
        {{- end }}
        helm:
          valueFiles:
          - values.yaml
          valuesObject:
            selfManagedHubSet: {{ .Values.selfManagedHubSet }}
            policy_namespace: {{ printf "policies-%s" .Release.Name }}
            {{- if .Values.hubClusterSets }}
            hubClusterSets:
            {{-  range $cluster, $clustervalue := .Values.hubClusterSets }}
              {{ $cluster }}:
                labels:
                {{-  range $labelkey, $labelvalue := $clustervalue.labels }}
                  {{ $labelkey }}: '{{ $labelvalue }}'
                {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.managedClusterSets }}
            managedClusterSets:
              {{-  range $cluster, $clustervalue := .Values.managedClusterSets }}
              {{ $cluster }}:
                labels:
                {{-  range $labelkey, $labelvalue := $clustervalue.labels }}
                  {{ $labelkey }}: '{{ $labelvalue }}'
                {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.clusters }}
            clusters:
              {{-  range $cluster, $clustervalue := .Values.clusters }}
              {{ $cluster }}:
                labels:
                {{-  range $labelkey, $labelvalue := $clustervalue.labels }}
                  {{ $labelkey }}: '{{ $labelvalue }}'
                {{- end }}
            {{- end }}
            {{- end }}
      ignoreDifferences:
      - group: "apps"
        kind: "Project"
        jsonPointers:
        - /metadata/annotations
        - /metadata/labels
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - RespectIgnoreDifferences=true
        - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ printf "policies-%s" .Release.Name }}
