apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: trident-snapshot-class
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates-raw: |
    - complianceType: mustonlyhave
      objectDefinition:
        apiVersion: snapshot.storage.k8s.io/v1
        kind: VolumeSnapshotClass
        metadata:
          name: trident-csi-snapclass
          annotations:
            snapshot.storage.kubernetes.io/is-default-class: "true"
        driver: csi.trident.netapp.io
        deletionPolicy: Delete
