---
{{- if .Values.gitops.repo.cluster_ca_bundle }}
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: {{ .Values.gitops.argoNamespace | default "openshift-gitops"}}
  name: user-ca-bundle
  labels:
    config.openshift.io/inject-trusted-cabundle: 'true'
{{- end }}
