{{- if .Values.gitops.repo.cluster_ca_bundle }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.gitops.argoNamespace }}
  name: user-ca-bundle
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
{{- end }}
