# This policy verifies the installation of the official & supported version of
# the OpenShift Logging on the managed clusters.
#
# Note that OpenShift 4.18 is required.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-logging-operator-install
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management, CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration, CA-7 Continuous Monitoring
spec:
{{ if .Values.autoshift.dryRun }}
  remediationAction: inform
{{ end }}
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: logging-operator-ns
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ .Values.logging.namespace }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-operator-logging
        spec:
          remediationAction: enforce
          severity: high
          complianceType: musthave
          operatorGroup:
            name: {{ .Values.logging.namespace }}
            namespace: {{ .Values.logging.namespace }}
            targetNamespaces:
              - {{ .Values.logging.namespace }}
          subscription:
            name: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/logging-subscription-name" | default "{{ .Values.logging.name }}" {{ "hub}}" }}'
            namespace: {{ .Values.logging.namespace }}
            # Source Selection Logic (evaluated on hub for each managed cluster):
            # 1. If cluster has explicit 'autoshift.io/logging-source' label → use that value
            # 2. Else if cluster has 'autoshift.io/disconnected-mirror: true':
            #    → use {source}{suffix} (e.g., redhat-operators-mirror)
            #    → suffix from 'autoshift.io/mirror-catalog-suffix' label, or default '-mirror'
            # 3. Else → use standard source (e.g., redhat-operators)
            source: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/logging-source" | default (ternary (printf "%s-%s" "{{ .Values.logging.source }}" (index .ManagedClusterLabels "autoshift.io/mirror-catalog-suffix" | default "mirror")) "{{ .Values.logging.source }}" (eq (index .ManagedClusterLabels "autoshift.io/disconnected-mirror") "true")) {{ "hub}}" }}'
            sourceNamespace: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/logging-source-namespace" | default "{{ .Values.logging.sourceNamespace }}" {{ "hub}}" }}'
            channel: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/logging-channel" | default "{{ .Values.logging.channel }}" {{ "hub}}" }}'
            startingCSV: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/logging-version" | default "" {{ "hub}}" }}'
            # Upgrade approval for subscription will be set based on if version is set not this flag
            # If version is set install plan is set to manual and only the version specified will be installed
          upgradeApproval: Automatic
          versions:
            - '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/logging-version" | default "" {{ "hub}}" }}'
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-logging-status
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: ClusterServiceVersion
                metadata:
                  namespace: {{ .Values.logging.namespace }}
                spec:
                  displayName: Red Hat OpenShift Logging
                status:
                  phase: Succeeded # check the csv status to determine if operator is running or not
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-logging-operator-install
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/logging'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-logging-operator-install
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-logging-operator-install
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-logging-operator-install
    apiGroup: policy.open-cluster-management.io
    kind: Policy
