apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.28.1
    releaseName: vault
    namespace: vault
    skipTests: true
    valuesInline:
      server:
        image:
          tag: '{{hub index .ManagedClusterLabels "autoshift.io/vault-version" | default "1.17.2" hub}}'
        standalone:
          enabled: true
        dataStorage:
          enabled: false
      injector:
        enabled: false
