apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-allowed-image-registries
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
{{ if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{ end }}
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: set-allowed-registries
        spec:
          remediationAction: enforce
          severity: high
          object-templates-raw: |
            # Build list of allowed registries
            {{ `{{hub-` }} $cfg := fromConfigMap `{{ $.Values.policy_namespace }}` (print .ManagedClusterName `.rendered-config`) `config` | default `{}` | fromYaml {{ `hub}}` }}
            {{ `{{hub-` }} $allowedRegistries := list {{ `hub}}` }}
            {{ `{{hub-` }} range $item := (index $cfg `default-allowed-registries` | default (list))  {{ `hub}}` }}
              {{ `{{hub-` }} $allowedRegistries = append $allowedRegistries $item {{ `hub}}` }}
            {{ `{{hub-` }} end {{ `hub}}` }}
            {{ `{{hub-` }} range $item := (index $cfg `clusterset-allowed-registries` | default (list))  {{ `hub}}` }}
              {{ `{{hub-` }} $allowedRegistries = append $allowedRegistries $item {{ `hub}}` }}
            {{ `{{hub-` }} end {{ `hub}}` }}
            {{ `{{hub-` }} range $item := (index $cfg `cluster-allowed-registries` | default (list))  {{ `hub}}` }}
              {{ `{{hub-` }} $allowedRegistries = append $allowedRegistries $item {{ `hub}}` }}
            {{ `{{hub-` }} end {{ `hub}}` }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: Image 
                metadata:
                  name: cluster
                spec:
                  allowedRegistriesForImport: 
                    {{ `{{hub-` }} range $registry := (index $allowedRegistries | default (list)) {{ `hub}}` }}
                    - domainName: {{ `{{hub` }} index $registry `domainName` {{ `hub}}` }}
                      insecure: {{ `{{hub` }} index $registry `insecure` | default `false` {{ `hub}}` }}
                    {{ `{{hub- end hub}}` }}
                  registrySources:
                    allowedRegistries:
                      {{ `{{hub-` }} range $registry := (index $allowedRegistries | default (list)) {{ `hub}}` }}
                      - {{ `{{hub` }} index $registry `domainName` {{ `hub}}` }}
                      {{ `{{hub- end hub}}` }}

---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-allowed-image-registries
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/manual-remediations'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-allowed-image-registries
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-allowed-image-registries
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-allowed-image-registries
    apiGroup: policy.open-cluster-management.io
    kind: Policy
