{{- if eq "" (.Values.policyNamespace | default "") }}
  {{- fail "policyNamespace value must be defined" }}
{{- else if eq "" (.Values.secretSourceNamespace | default "") }}
  {{- fail "secretSourceNamespace value must be defined" }}
{{- end }}
{{- $policyName := printf "%s-%s" .Release.Name "secrets" }}
{{- $clusterName := $.Values.clusterName | default $.Release.Name }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
  name: {{ $policyName }}
  namespace: {{ $.Values.policyNamespace }}
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ $policyName }}
        spec:
          remediationAction: enforce
          severity: high
          object-templates-raw: | 
            {{- range $idx, $hostname := .Values.hosts }}
            {{-  $hostValues := index $.Values.all_hosts $hostname }}
            {{- if empty $hostValues }}
            {{- fail (printf "Unknown host: %s encountered in host list" $hostname) }}
            {{- end }}
            {{- $bmcSecretNamespace := (index (index $hostValues "bmcCredentialRef" | default dict) "namespace") | default $.Values.secretSourceNamespace }}
            {{- $bmcSecretName := (index (index $hostValues "bmcCredentialRef" | default dict) "name") | default (index $.Values.bmcCredentialRef)  | default "default-bmc-cred" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                type: Opaque
                metadata: 
                  name: {{ $hostname }}-bmc-cred
                  namespace: {{ $.Values.clusterName }}
                data: '{{ "{{" }} copySecretData  "{{ $bmcSecretNamespace }}" "{{ $bmcSecretName }}" | toLiteral {{ "}}" }}'
            {{- end  }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                type: kubernetes.io/dockerconfigjson
                metadata: 
                  name: {{ $clusterName }}-pull-secret
                  namespace: {{ $.Values.clusterName }}
                data: '{{ "{{" }} copySecretData "{{ $.Values.secretSourceNamespace }}" "{{ $.Values.pullSecretRef | default "default-pull-secret" }}" | toLiteral {{ "}}" }}'
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-{{ $policyName }}
  namespace: {{ $.Values.policyNamespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
spec:
  clusterSets:
    - {{ $.Values.hubClusterSet }}
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-{{ $policyName }}
  namespace: {{ .Values.policyNamespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
placementRef:
  name: placement-{{ $policyName }}
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: {{ $policyName }}
    apiGroup: policy.open-cluster-management.io
    kind: Policy
