
{{- $clusterName := $.Values.clusterName | default $.Release.Name }}
{{- $pullSecretName := printf "pullsecret-%s" $.Values.clusterName }}
{{- $clusterName := $.Values.clusterName | default $.Release.Name }}
{{- $bmcCredentialSecret := printf "bmc-credentials-" $clusterName }}
{{- $imageSet := ($.Values.clusterImageSet | default (printf "%s-%s" "openshift-image-set" $.Values.openshiftVersion)) }}
{{- $controlPlaneCount := $.Values.controlPlaneAgents | default 3 | int }}
{{- $workerCount := $.Values.workerAgents | default (sub ($.Values.hosts | len )  $controlPlaneCount) }}
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: agent-cluster-install
  namespace: {{ $clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  AgentClusterInstall: |-
    apiVersion: extensions.hive.openshift.io/v1beta1
    kind: AgentClusterInstall
    metadata:
      annotations:
      name: {{ $clusterName }}
      namespace: {{ $clusterName }}
    spec:
      clusterDeploymentRef:
        name: {{ $clusterName }}
      imageSetRef:
        name: {{ $imageSet }}
    {{- if (gt $controlPlaneCount 1) }}
      platformType: BareMetal 
      apiVIP: {{ $.Values.apiVip }}
      ingressVIP: {{ $.Values.ingressVip }}
      mastersSchedulable: {{ $.Values.mastersSchedulable | default false }}
      provisionRequirements:
        controlPlaneAgents: {{ $controlPlaneCount }}
        workerAgents: {{ $workerCount }}
    {{- else }}
      provisionRequirements:
        controlPlaneAgents: 1
    {{- end }}
      networking:
    {{- if (eq $controlPlaneCount 1) }}
        userManagedNetworking: true
    {{- end }}
        clusterNetwork:
        - cidr: {{ $.Values.networking.clusterNetwork.cidr }}
          hostPrefix: {{ $.Values.networking.clusterNetwork.hostPrefix }}
        machineNetwork:
        - cidr: {{ $.Values.networking.machineNetwork.cidr }}
        serviceNetwork:
      {{- range $_, $network := $.Values.networking.serviceNetwork }}
        - {{ $network }}
      {{- end }}
      sshPublicKey: {{ $.Values.sshPublicKey | default "" }}
