{{- $pullSecretName := printf "pullsecret-%s" $.Values.clusterName }}
{{- $clusterName := $.Values.clusterName | default $.Release.Name }}
{{- $bmcCredentialSecret := printf "bmc-credentials-" $clusterName }}
{{- $imageSet := printf "%s-%s" "openshift-image-set-" $.Values.openshiftVersion }}
{{- range $_, $host_key := $.Values.hosts }}
  {{- $host := index $.Values.all_hosts $host_key }}
  {{- if not (empty $host) }}
    {{- $bmcEndpoint := ($host.bmcEndpoint | default $.Values.bmcEndpoint) }}
    {{- $hostname := $host_key }}
    {{- $bmcAddress := printf "%s://%s%s" $host.bmcPrefix $host.bmcIP $bmcEndpoint }}
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: bmh-{{ $hostname }}
  namespace: {{ $clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  BareMetalHost: |-
    apiVersion: metal3.io/v1alpha1
    kind: BareMetalHost
    metadata:
      name: {{ $hostname }}
      namespace: {{ $clusterName }}
      annotations:
        inspect.metal3.io: disabled
        bmac.agent-install.openshift.io/hostname: {{ $hostname }}
      labels:
        infraenvs.agent-install.openshift.io: {{ $clusterName }}
    spec:
      automatedCleaningMode: disabled
      bmc:
        address: '{{ $bmcAddress }}'
        credentialsName: {{ $hostname }}-bmc-cred
        disableCertificateVerification: true
      bootMACAddress: '{{ $host.bootMACAddress }}'
      customDeploy:
        method: start_assisted_install
      online: true
      {{- else }}
        {{- fail (printf "All desired hosts must be present in the all_hosts dictionary, %s not found" $host_key) }}
      {{- end }}
    {{ end }}
