{{- $pullSecretName := printf "pullsecret-%s" $.Values.clusterName }}
{{- $clusterName := $.Values.clusterName | default $.Release.Name }}
{{- $bmcCredentialSecret := printf "bmc-credentials-" $clusterName }}
{{- $imageSet := printf "%s-%s" "openshift-image-set-" $.Values.openshiftVersion }}
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: cluster-deployment
  namespace: {{ $clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  ClusterDeployment: |-
    apiVersion: hive.openshift.io/v1
    kind: ClusterDeployment
    metadata:
      name: {{ $clusterName }}
      namespace: {{ $clusterName }}
      labels:
        cluster.open-cluster-management.io/clusterset: default
        hive.openshift.io/cluster-platform: agent-baremetal
    spec:
      baseDomain: {{ $.Values.baseDomain }}
      clusterInstallRef:
        group: extensions.hive.openshift.io
        kind: AgentClusterInstall
        name: {{ $clusterName }} 
        version: v1beta1
      clusterName: {{ $clusterName }}
      controlPlaneConfig:
        servingCertificates: {}
      platform:
        agentBareMetal:
          agentSelector:
            matchLabels:
              agentBareMetal-generated-infraenv-ai-flow: {{ $clusterName }}-{{ $clusterName }}
      pullSecretRef:
        name: {{ $clusterName }}-pull-secret
