{{/*
{{- $pullSecretName := printf "pullsecret-%s" $.Values.clusterName }}
{{- $bmcCredentialSecret := printf "bmc-credentials-" $clusterName }}
{{- $imageSet := printf "%s-%s" "openshift-image-set-" $.Values.openshiftVersion }}
*/}}
{{- $clusterName := $.Values.clusterName | default $.Release.Name }}
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: infra-env
  namespace: {{ $clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  InfraEnv: |-
    apiVersion: agent-install.openshift.io/v1beta1
    kind: InfraEnv
    metadata:
      labels:  
        networkType: dhcp 
      name: {{ $clusterName }}
      namespace: {{ $clusterName }}
    spec:
      agentLabels:
        agentBareMetal-generated-infraenv-ai-flow: {{ $clusterName }}-{{ $clusterName }}
      additionalTrustBundle: |
      {{- $.Values.caTrustBundle | default "" | nindent 8 }}
    {{- if not (empty $.Values.ntpSources) }}
      additionalNTPSources: 
      {{- range $idx, $ntpSource := $.Values.ntpSources }}
        - {{ $ntpSource }}
      {{- end }}
    {{- end }}
      clusterRef:
        name: {{ $clusterName }}
        namespace: {{ $clusterName }} 
      cpuArchitecture: {{ $.Values.cpuArch }}
      pullSecretRef:
        name: {{ $clusterName }}-pull-secret
      sshAuthorizedKey: {{ $.Values.sshPublicKey | default "" }}
      nmStateConfigLabelSelector:
        matchLabels:
         infraenvs.agent-install.openshift.io: {{ $clusterName }}
