{{- $clusterName := $.Values.clusterName | default $.Release.Name }}
apiVersion: v1
kind: ConfigMap
metadata: 
  name: managed-cluster
  namespace: {{ $clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  ManagedCluster: |-
    apiVersion: cluster.open-cluster-management.io/v1
    kind: ManagedCluster
    metadata:
      name: {{ $clusterName }}
    spec:
      hubAcceptsClient: true
