{{- define "random.mac" -}}
{{- printf "%sA:%sB:%sC:%sD:%sE:%sF" (randNumeric 1) (randNumeric 1) (randNumeric 1) (randNumeric 1) (randNumeric 1) (randNumeric 1) -}}
{{- end -}}
{{- $clusterName := $.Values.clusterName | default $.Release.Name }}
{{- range $_, $host_key := $.Values.hosts }}
  {{- $host := index $.Values.all_hosts $host_key }}
  {{- if not (empty $host) }}
    {{- $hostname := $host_key }}
    {{- range $_, $interface := $host.interfaces }}
      {{- if  eq $interface.macAddress "" -}}
        {{- $_ := set $interface "macAddress" (include "random.mac" .) -}}
      {{- end -}}
    {{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: nmstate-{{ $hostname }}
  namespace: {{ $clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  NMStateConfig: |-
    apiVersion: agent-install.openshift.io/v1beta1
    kind: NMStateConfig
    metadata:
      labels:
        infraenvs.agent-install.openshift.io: {{ $.Values.clusterName }}
      name: {{ $hostname }}
      namespace: {{ $.Values.clusterName }}
    spec:
      config:
        dns-resolver:
          config:
            server:
        {{- range $_, $dnsServer := $.Values.networking.dnsServers }}
              - {{ $dnsServer }}
        {{- end }}
        interfaces:
        {{- if ((index $.Values "useBond") | default true) }}
          {{- $bondName := (printf "%s%s" "bond0." (toString ($.Values.networking.vlan | default 0))) }}
          - ipv4:
              dhcp: false
              enabled: false
            ipv6:
              enabled: false
            link-aggregation:
              mode: active-backup
              port:
          {{- range $idx, $interface := $host.interfaces }}
            {{- if not (index $interface "disabled" | default false) }}
                - {{ (index $interface "name") | default (printf "%s%s" "eno" (toString (add1 $idx))) }}
            {{- end }}
          {{- end }}
            mac-address: {{ index $host "primaryMac" | default (index $host.interfaces 0 "macAddress") }}
            name: bond0
            state: up
            type: bond
          - ipv4:
              address:
                - ip: {{ $host.IP }}
                  prefix-length: {{ $.Values.networking.machinePrefixLength }}
              dhcp: {{ index $.Values "useDHCP" | default false }}
              enabled: true
            ipv6:
              enabled: false
            name: {{ $bondName }}
            state: up
            type: vlan
            vlan:
              base-iface: bond0
              id: {{ $.Values.networking.vlan | default 0 }}
        routes:
          config:
            - destination: 0.0.0.0/0
              next-hop-address: {{ $.Values.networking.defaultGateway }}
              next-hop-interface: {{ $bondName }}
        {{- end }}
      interfaces:
        {{- range $idx, $interface := $host.interfaces }}
        - macAddress: {{ $interface.macAddress | default }}
          name: {{ (index $interface "name") | default (printf "%s%s" "eno" (toString (add1 $idx))) }}
        {{- end }}
      {{- else }}
        {{- fail (printf "All desired hosts must be present in the 'all_hosts' dictionary, %s not found" $host_key) }}
      {{- end }}
    {{- end }}

