
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-cert-manager
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
{{ if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{ end }}
  dependencies:
    - name: policy-cert-manager-operator-install
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  disabled: false
  policy-templates:
    - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: cert-manager
      spec:
        remediationAction: inform
        severity: high
        object-templates-raw: |

          {{ "{{hub-" }} $configs := (index (fromConfigMap "{{ $.policy_namespace }}" (printf "%s.%s" .ManagedClusterName "rendered-config" "config") | fromYaml) "cert-manager" | default dict) {{ "hub}}" }}
          - complianceType: musthave
            apiVersion: operator.openshift.io/v1alpha1
            kind: CertManager
            metadata:
              name: cluster
            spec:
              logLevel: {{ "{{hub" }} index $configs "logLevel" | default "Normal" {{ "hub}}" }}
              managementState: Managed
              operatorLogLevel: {{ "{{hub" }} index $configs "operatorLogLevel" | default "Normal" {{ "hub}}" }}
              unsupportedConfigOverrides:
                controller:
                  args:
                    {{ "{{hub" }} range $idx, $override := (index $configs "overrides" | default (list)) {{ "hub}}" }}
                    - {{ "{{hub" }} $arg {{ "hub}}" }}
                    {{ "{{hub" }} end {{ "hub}}" }}
