{{- $policyName := "policy-dynatrace-virt-annotations" }}
{{- $placementName := "placement-policy-dynatrace-virt-annotations" }}

apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $policyName }}
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: enforce
  dependencies:
    - name: policy-dynatrace-deploy-dynakube
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-dynatrace-kubevirt-pod-annotations
        spec:
          remediationAction: enforce
          severity: low
          namespaceSelector:
            include:
              - openshift-cnv
          object-templates-raw: |
              {{ "{{" }}- range $pod := (lookup "v1" "Pod" "openshift-cnv" "").items {{ "}}" }}
              {{ "{{" }}- if $pod.metadata.labels {{ "}}" }}
              {{ "{{" }}- if index $pod.metadata.labels "prometheus.kubevirt.io" {{ "}}" }}
              - complianceType: musthave
                objectDefinition:
                  apiVersion: v1
                  kind: Pod
                  metadata:
                    name: {{ "{{" }} $pod.metadata.name {{ "}}" }}
                    namespace: openshift-cnv
                    annotations:
                      metrics.dynatrace.com/scrape: "true"
                      metrics.dynatrace.com/port: "8443"
              {{ "{{" }}- end {{ "}}" }}
              {{ "{{" }}- end {{ "}}" }}
              {{ "{{" }}- end {{ "}}" }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ $placementName }}
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/dynatrace'
              operator: In
              values:
              - 'true'
            - key: 'autoshift.io/virt'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ $placementName }}
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: {{ $placementName }}
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: {{ $policyName }}
    apiGroup: policy.open-cluster-management.io
    kind: Policy