# Default values for openshift-virtualization.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
virt:
    name: kubevirt-hyperconverged
    namespace: openshift-cnv
    channel: stable
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# virt<bool>: 'true' or 'false' - Enable OpenShift Virtualization (KubeVirt)
#
# Configuration:
# virt-channel<String>: Operator channel (default: 'stable')
# virt-install-plan-approval<String>: 'Automatic' or 'Manual' (default: 'Automatic')
# virt-source<String>: Operator catalog source (default: 'redhat-operators')
# virt-source-namespace<String>: Catalog namespace (default: 'openshift-marketplace')
#
# Note: Enables running virtual machines on OpenShift using KubeVirt technology
# Requires compatible hardware with virtualization extensions
#
# Examples:
# autoshift.io/virt: 'true'
# autoshift.io/virt-channel: 'stable'
# autoshift.io/virt-install-plan-approval: 'Automatic'