# namespace to put all policies created by the application into
policyNamespace: "policy-cluster-installs"
# namespace to source secrets from for replication (can be overrideen for bmc credentials)
secretSourceNamespace: "cluster-install-secrets"
# Cluster set representing the hub cluster this will run on, it ONLY works with that, this cannot be another hub cluster or managed cluster
hubClusterSet: "hubofhubs"
# boolean toggle for forcibly recreating BMH objects when a change is detected
recreateHosts: "true"
caTrustBundle: |-
