apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-central-hub
  namespace: ${POLICY_NAMESPACE}
spec:
  # Central and anything that manages it. NotIn 'false' so a cluster with no acs-central label still runs Central, the default.
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/acs'
              operator: In
              values:
                - 'true'
            - key: 'autoshift.io/cluster-type'
              operator: In
              values:
                - 'hub'
            - key: 'autoshift.io/acs-central'
              operator: NotIn
              values:
                - 'false'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
