apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-auth-hub
  namespace: ${POLICY_NAMESPACE}
spec:
  # Declarative auth config. Skipped entirely when acs-auth-provider is 'none'.
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/acs'
              operator: In
              values:
                - 'true'
            - key: 'autoshift.io/cluster-type'
              operator: In
              values:
                - 'hub'
            - key: 'autoshift.io/acs-central'
              operator: NotIn
              values:
                - 'false'
            - key: 'autoshift.io/acs-auth-provider'
              operator: NotIn
              values:
                - 'none'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
