apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-default-policies-hub
  namespace: ${POLICY_NAMESPACE}
spec:
  # Baseline SecurityPolicy resources. Opt-in, so In 'true' rather than NotIn.
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/acs'
              operator: In
              values:
                - 'true'
            - key: 'autoshift.io/cluster-type'
              operator: In
              values:
                - 'hub'
            - key: 'autoshift.io/acs-central'
              operator: NotIn
              values:
                - 'false'
            - key: 'autoshift.io/acs-default-policies'
              operator: In
              values:
                - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
