# Kiali Operator
# Portable Helm chart - works with or without ACM
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.kiali.name }}
  namespace: {{ .Values.kiali.namespace }}
spec:
  channel: {{ .Values.kiali.channel }}
  name: {{ .Values.kiali.name }}
  source: {{ .Values.kiali.source }}
  sourceNamespace: {{ .Values.kiali.sourceNamespace }}
