{{- $files := .Files.Glob "files/peers/**" }}
{{- if $files }}
# This policy verifies the installation of the official & supported version of
# the bgp NodeNetworkConfigurationPolicy on the managed clusters.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-peer-configmaps
  namespace: {{ .Values.policy_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    policy.open-cluster-management.io/standards: AutoShiftv2
    policy.open-cluster-management.io/categories: Kubernetes MetalLB Operator
    policy.open-cluster-management.io/controls: OpenShift Standard
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: peer-configmap
          namespace: policies-autoshift
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            {{- range $path, $_ := $files }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: peer-{{ ($path | trimPrefix "files/peers/" | split ".")._0 }}
                  namespace: {{ $.Values.policy_namespace }}
                data:
                  adv: {{ $.Files.Get $path | b64enc }}
            {{- end }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-peer-configmap
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/metallb-bgp'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-peer-configmap
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-peer-configmap
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-peer-configmaps
    apiGroup: policy.open-cluster-management.io
    kind: Policy
{{- end }}
