# Default values for image registry
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
imageregistry: 
  clusterSets:
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

# Labels
# autoshift.io/imageregistry<bool>: If not set the imageregistry will not be managed. default false
# autoshift.io/imageregistry-management-state<bool>: Managed or Removed. default Managed
# autoshift.io/imageregistry-replicas<bool>: If set higher than 1, must have ReadWrite Many or s3 storage type. default 1
# autoshift.io/imageregistry-storage-type<String>: s3 or pvc. s3 will use openshift-storage.noobaa.io storage class. pvc will use the storage class defined in autoshift.io/imageregistry-pvc-storage-class
# autoshift.io/imageregistry-s3-region<String>: us-east-1, us-west-2, etc. default us-east-1
# autoshift.io/imageregistry-pvc-access-mode<String>: ReadWriteOnce, ReadWriteMany
# autoshift.io/imageregistry-pvc-size<String>: size of pvc eg. 100Gi
# autoshift.io/imageregistry-pvc-storage-class<String>: ocs-storagecluster-ceph-rbd, gp2, gp3, etc
# autoshift.io/imageregistry-pvc-volume-mode<String>: volumeMode defines what type of volume is required by the claim. Block or Filesystem
# autoshift.io/imageregistry-rollout-strategy<String>: Recreate or RollingUpdate. If replicas is set to 1, Recreate must be used.
