---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-tempo

policyDefaults:
  namespace: ${POLICY_NAMESPACE}
  remediationAction: enforce
  severity: high
  consolidateManifests: false
  placement:
    placementName: placement-policy-tempo

policies:
  - name: policy-tempo
    manifests:
      - path: policy-manifests/tempo
