apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-ldap-bind-secret
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
{{- if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{- end }}
  disabled: false
  hubTemplateOptions:
    serviceAccountName: secret-reader
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ldap-bind-secret
          namespace: {{ .Values.policy_namespace }}
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates-raw: |
            {{ "{{hub" }} $secret := index .ManagedClusterLabels "autoshift.io/ldap-groupsync-secret" | default "{{ .Values.ldap_groupsync_secret }}" {{ "hub}}" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: ldap-bind-password
                  namespace: openshift-config
                type: Opaque
                data:
                  bindPassword: {{ "{{hub" }} fromSecret (index .ManagedClusterLabels `autoshift.io/auth-secrets-namespace`) $secret "bindPassword" {{ "hub}}" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ "{{hub" }} $secret {{ "hub}}" }}
                  namespace: {{ .Values.ldap_groupsync_namespace }}
                type: Opaque
                data:
                  bindDN: {{ "{{hub" }} fromSecret (index .ManagedClusterLabels `autoshift.io/auth-secrets-namespace`) $secret "bindDN" {{ "hub}}" }}
                  bindPassword: {{ "{{hub" }} fromSecret (index .ManagedClusterLabels `autoshift.io/auth-secrets-namespace`) $secret "bindPassword" {{ "hub}}" }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-ldap-bind-secret
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/create-ldap-bind-secret'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-ldap-bind-secret
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-ldap-bind-secret
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-ldap-bind-secret
    apiGroup: policy.open-cluster-management.io
    kind: Policy
