apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-oauth
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
{{- if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{- end }}
  dependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      kind: Policy 
      name: policy-oauth-ca-bundle
      namespace: {{ .Values.policy_namespace }}
      compliance: Compliant
  disabled: false
  hubTemplateOptions:
    serviceAccountName: secret-reader
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: oauth
        spec:
          remediationAction: enforce
          severity: high
          object-templates-raw : |
            # Fetch ldap secret name
            {{ "{{hub-" }} $cfg := fromConfigMap "{{ $.Values.policy_namespace }}" (print .ManagedClusterName ".rendered-config") "config" | default "{}" | fromYaml {{ "hub}}" }}
            {{ "{{hub-" }} $ldapConfig := index $cfg `ldap` | default (dict) {{ "hub}}" }}
            {{ "{{hub-" }} $secret := index .ManagedClusterLabels "autoshift.io/ldap-groupsync-secret" | default "{{ .Values.ldap_groupsync_secret }}" {{ "hub}}" }}
            # Get bindDN
            {{ "{{hub" }} $bindDN := fromSecret (index .ManagedClusterLabels `autoshift.io/auth-secrets-namespace`) $secret "bindDN" {{ "hub}}" }}

            # Add Identity Providers to OAuth object
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OAuth
                metadata:
                  name: cluster
                spec:
                  identityProviders:
                    - type: LDAP
                      mappingMethod: claim
                      name: VA Active Directory
                      ldap:
                        attributes:
                          email: []
                          id:
                            - userPrincipalName
                          name:
                            - displayName
                          preferredUsername:
                            - userPrincipalName
                        bindDN: {{ "{{hub" }} $bindDN | base64dec | quote {{ "hub}}" }}
                        bindPassword:
                          name: ldap-bind-password
                        ca:
                          name: ldap-ca
                        insecure: false
                        url: '{{ "{{hub" }} index $ldapConfig `url` {{ "hub}}" }}/{{ "{{hub" }} index $ldapConfig `url-search` {{ "hub}}" }}'
                  tokenConfig:
                    accessTokenInactivityTimeout: 10m0s
                    accessTokenMaxAgeSeconds: 28800
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: oauth-test
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterOperator
                metadata:
                  name: authentication
                status:
                  conditions:
                    - message: All is well
                      reason: AsExpected
                      status: 'False'
                      type: Degraded
                    - message: 'AuthenticatorCertKeyProgressing: All is well'
                      reason: AsExpected
                      status: 'False'
                      type: Progressing
                    - message: All is well
                      reason: AsExpected
                      status: 'True'
                      type: Available
                    - message: All is well
                      reason: AsExpected
                      status: 'True'
                      type: Upgradeable
                    - reason: NoData
                      status: Unknown
                      type: EvaluationConditionsDetected
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-oauth
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/oauth'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-oauth
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-oauth
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-oauth
    apiGroup: policy.open-cluster-management.io
    kind: Policy
