apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-initialize-postgres-database
  namespace: {{ .Values.policy_namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "3"
    policy.open-cluster-management.io/depends-on: policy:{{ .Values.policy_namespace }}/policy-create-postgres-database
spec:
  dependencies:
    - name: policy-create-postgres-database
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  remediationAction: enforce
  disabled: false
  policy-templates:
    {{- if not .Values.ignoreHelmHooks }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: initialize-hapostgres-database
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            # Initialize postgres database to enable installation of RHBK
            - complianceType: musthave
              objectDefinition:
                apiVersion: batch/v1
                kind: Job
                metadata:
                  name: {{ .Values.postgres.clusterName }}-db-init
                  namespace: {{ .Values.namespace }}
                spec:
                  backoffLimit: 6
                  template:
                    spec:
                      restartPolicy: OnFailure
                      initContainers:
                        - name: wait-for-postgres
                          image: {{ .Values.crunchy.postgrescli }}
                          command:
                            - /bin/sh
                            - -c
                            - |
                              until pg_isready -h {{ .Values.postgres.clusterName }}-primary.{{ .Values.namespace }}.svc.cluster.local -p 5432 -U postgres; do
                                echo "Waiting for primary database service on port 5432..."
                                sleep 5
                              done
                          env:
                            - name: PGPASSWORD
                              valueFrom:
                                secretKeyRef:
                                  name: {{ .Values.postgres.clusterName }}-pguser-postgres
                                  key: password
                      containers:
                        - name: db-init
                          image: {{ .Values.crunchy.postgrescli }}
                          command:
                            - /bin/sh
                            - -c
                            - |
                              psql -h {{ .Values.postgres.clusterName }}-primary.{{ .Values.namespace }}.svc.cluster.local -U postgres -d {{ .Values.postgres.dbUser.database }} -c "ALTER DATABASE \"{{ .Values.postgres.dbUser.database }}\" OWNER TO \"{{ .Values.postgres.dbUser.name }}\"; GRANT ALL PRIVILEGES ON DATABASE \"{{ .Values.postgres.dbUser.database }}\" TO \"{{ .Values.postgres.dbUser.name }}\";"
                          env:
                            - name: PGPASSWORD
                              valueFrom:
                                secretKeyRef:
                                  name: {{ .Values.postgres.clusterName }}-pguser-postgres
                                  key: password
                      securityContext:
                        runAsNonRoot: true
    {{- end }}

---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-initialize-postgres-database
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}

  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/rhbk'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placementbinding-policy-initialize-postgres-database
  namespace: {{ .Values.policy_namespace }}
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-policy-initialize-postgres-database
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: policy-initialize-postgres-database
