apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-trident-user-secret
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: AutoShiftv2
    policy.open-cluster-management.io/categories: Kubernetes MetalLB Operator
    policy.open-cluster-management.io/controls: OpenShift Standard
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: trident-user-secret
          namespace: policies-autoshift
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates-raw: |
            {{ "{{hub-" }} $secret_name := list {{ "hub}}" }}
            {{ "{{hub-" }} range $label, $labelvalue := .ManagedClusterLabels {{ "hub}}" }}
              {{ "{{hub-" }} if $label | hasPrefix "autoshift.io/trident-creds-secret" {{ "hub}}" }}
                {{ "{{hub-" }} $secret_name = append $secret_name $labelvalue {{ "hub}}" }}
              {{ "{{hub-" }} end {{ "hub}}" }}
            {{ "{{hub-" }} end {{ "hub}}" }}
            {{ "{{hub-" }} if not (eq 0 (len $secret_name)) {{ "hub}}" }}
              {{ "{{hub-" }} range $secret_name {{ "hub}}" }}
                {{ "{{hub-" }} $secret := ((lookup "v1" "Secret" "{{ $.Values.policy_namespace }}" .).data) {{ "hub}}" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ "{{hub"}} . {{ "hub}}" }}
                  namespace: {{ .Values.trident.namespace }}
                type: Opaque
                data:
                  username: {{ "{{hub" }} $secret.username {{ "hub}}" }}
                  password: {{ "{{hub" }} $secret.password {{ "hub}}" }}
              {{ "{{hub-"}} end {{ "hub}}" }}
            {{ "{{hub-"}} end {{ "hub}}" }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-trident-user-secret
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/trident'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-trident-user-secret
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-trident-user-secret
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-trident-user-secret
    apiGroup: policy.open-cluster-management.io
    kind: Policy
