apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-trident-user-secret
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: AutoShiftv2
    policy.open-cluster-management.io/categories: Trident
    policy.open-cluster-management.io/controls: OpenShift Standard
spec:
  disabled: false
  dependencies:
    - name: policy-trident-operator-install
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: trident-user-secret
          namespace: policies-autoshift
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates-raw: |
            {{ "{{hub"}} $secret := (index .ManagedClusterLabels "autoshift.io/trident-creds-secret") {{ "hub}}" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ "{{hub"}} $secret {{ "hub}}" }}
                  namespace: {{ .Values.trident.namespace }}
                type: Opaque
                data:
                  username: {{`{{ fromSecret "`}}{{ .Values.policy_namespace }}{{`" "{{hub $secret hub}}" "username" }}`}}
                  password: {{`{{ fromSecret "`}}{{ .Values.policy_namespace }}{{`" "{{hub $secret hub}}" "password" }}`}}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-trident-user-secret
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/trident-creds-secret'
              operator: Exists
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-trident-user-secret
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-trident-user-secret
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-trident-user-secret
    apiGroup: policy.open-cluster-management.io
    kind: Policy