apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-trident-create-role
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
{{- if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{- end }}
  disabled: false
  dependencies:
    - name: policy-trident-orchestrator
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: trident-create-role
          namespace: {{ .Values.policy_namespace }}
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates-raw: |
            - complianceType: mustonlyhave
              objectDefinition:
                kind: ClusterRole
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: storage-trident-ro
                rules:
                  - verbs:
                      - get
                      - watch
                      - list
                    apiGroups:
                      - trident.netapp.io
                    resources:
                      - '*'
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-trident-create-role
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := .Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := .Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/trident'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-trident-create-role
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-trident-create-role
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-trident-create-role
    apiGroup: policy.open-cluster-management.io
    kind: Policy
