---
# Template file - variables substituted by CMP before kustomize runs
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-quay

placementBindingDefaults:
  name: policy-quay

policyDefaults:
  namespace: ${POLICY_NAMESPACE}
  configurationPolicyAnnotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring

  consolidateManifests: true
  orderManifests: false
  orderPolicies: false
  generatePlacementWhenInSet: false
  pruneObjectBehavior: None
  complianceType: musthave
  severity: critical
  informGatekeeperPolicies: false
  evaluationInterval:
    compliant: 10s
    noncompliant: 10s

  placement:
    placementName: placement-policy-quay-configure

policies:
  - name: policy-quay-configure
    description: Configure Quay
    remediationAction: enforce
    dependencies:
      - name: policy-quay-deploy
    manifests:
      - path: policy-manifests/quay-configure
