---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-local-storage

policyDefaults:
  namespace: ${POLICY_NAMESPACE}
  remediationAction: enforce
  severity: high
  consolidateManifests: false
  placement:
    placementName: placement-policy-local-storage

policies:
  - name: policy-local-storage
    manifests:
      - path: policy-manifests/local-storage
