apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: cluster-infra-monitoring
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  pruneObjectBehavior: None
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: cluster-monitoring-config
          namespace: openshift-monitoring
        data:
          config.yaml: |+
                    alertmanagerMain:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        effect: NoExecute
                    prometheusK8s:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        effect: NoExecute
                    prometheusOperator:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        effect: NoExecute
                    k8sPrometheusAdapter:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        effect: NoExecute
                    kubeStateMetrics:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        effect: NoExecute
                    telemeterClient:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        effect: NoExecute
                    openshiftStateMetrics:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        effect: NoExecute
                    thanosQuerier:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        effect: NoExecute
                    monitoringPlugin:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        effect: NoExecute
