apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: create-infra-image-registry
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  pruneObjectBehavior: None
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: imageregistry.operator.openshift.io/v1
        kind: Config
        metadata:
          name: cluster
        spec:
          nodeSelector:
            node-role.kubernetes.io/infra: ""
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/infra
            - effect: NoExecute
              key: node-role.kubernetes.io/infra
