{{- range $clusterSet, $value := .Values.managedClusterSets }}
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: {{ $clusterSet }}
  namespace: "{{ $.Values.policy_namespace }}"
spec:
  clusterSet: {{ $clusterSet }}
{{ end }}
{{- range $clusterSet, $value := .Values.hubClusterSets }}
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: {{ $clusterSet }}
  namespace: "{{ $.Values.policy_namespace }}"
spec:
  clusterSet: {{ $clusterSet }}
{{ end }}