apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.policy_namespace }}
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
    autoshift.io/createdByAutoshift: "true"
