apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: acm-provisioner
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: ${EVAL_COMPLIANT}
    noncompliant: ${EVAL_NONCOMPLIANT}
  object-templates:
  - complianceType: musthave
    objectDefinition:
      apiVersion: metal3.io/v1alpha1
      kind: Provisioning
      metadata:
        name: provisioning-configuration
      spec:
        provisioningNetwork: Disabled
        watchAllNamespaces: true
