apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: gitlab-object-storage
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: gitlab-openshift-service-ca
          namespace: gitlab-system
          annotations:
            service.beta.openshift.io/inject-cabundle: "true"
    - complianceType: musthave
      objectDefinition:
        apiVersion: objectbucket.io/v1alpha1
        kind: ObjectBucketClaim
        metadata:
          name: gitlab-objectstorage
          namespace: gitlab-system
        spec:
          generateBucketName: gitlab
          storageClassName: openshift-storage.noobaa.io
