---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-node-feature-discovery

policyDefaults:
  namespace: ${POLICY_NAMESPACE}
  remediationAction: enforce
  severity: high
  consolidateManifests: false
  placement:
    placementName: placement-policy-node-feature-discovery

policies:
  - name: policy-node-feature-discovery
    manifests:
      - path: policy-manifests/node-feature-discovery
