apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: trident-orchestrator
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates-raw: |
    - complianceType: mustonlyhave
      objectDefinition:
        apiVersion: trident.netapp.io/v1
        kind: TridentOrchestrator
        metadata:
          name: trident
        spec:
          IPv6: false
          debug: true
          nodePrep: []
          imagePullSecrets: []
          imageRegistry: ''
          namespace: trident
          silenceAutosupport: false
