apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: aap-trusted-ca-configmap
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates-raw: |
    # ConfigMap for trusted-cabundle (external services like Red Hat SSO)
    - complianceType: musthave
      objectDefinition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: aap-trusted-ca
          namespace: ansible-automation-platform
          labels:
            config.openshift.io/inject-trusted-cabundle: "true"
