# Not a STIG rule. The Samples Operator pulls imagestreams from registry.redhat.io, which fails
# noisily once ocp-allowed-registries restricts the registry list.
object-templates-raw: |
  {{hub- $cm := ((lookup "v1" "ConfigMap" .PolicyMetadata.namespace (printf "%s.rendered-config" .ManagedClusterName)) | default dict) hub}}
  {{hub- $cfg := ((dig "data" "config" "" $cm) | fromYaml | default dict) hub}}
  {{hub- if (dig "manualRemediations" "removeSamplesOperator" false $cfg) hub}}
  - complianceType: musthave
    objectDefinition:
      apiVersion: samples.operator.openshift.io/v1
      kind: Config
      metadata:
        name: cluster
      spec:
        managementState: Removed
  {{hub- end hub}}
