# Not a STIG rule. The Samples Operator pulls imagestreams from registry.redhat.io, which fails
# noisily once ocp-allowed-registries restricts the registry list.
object-templates-raw: |
  - complianceType: musthave
    objectDefinition:
      apiVersion: samples.operator.openshift.io/v1
      kind: Config
      metadata:
        name: cluster
      spec:
        managementState: Removed
