# OpenShift DNS Tolerations
# Portable Helm chart - works with or without ACM
# Configures DNS pods to tolerate all node taints
---
apiVersion: operator.openshift.io/v1
kind: DNS
metadata:
  name: default
spec:
  nodePlacement:
    tolerations:
    - operator: Exists
