apiVersion: v1
kind: Secret
metadata:
  name: dynatrace-activegate-token
  namespace: dynatrace
  annotations:
    kubernetes.io/service-account.name: dynatrace-activegate
type: kubernetes.io/service-account-token