# This policy enables the ODF console plugin on the managed clusters.
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: policy-odf-console-plugin-enable
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: operator.openshift.io/v1
        kind: Console
        metadata:
          name: cluster
        spec:
          plugins:
            - odf-console
