apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: storage-cluster-install-standalone
spec:
  remediationAction: ${REMEDIATION}
  severity: high
  evaluationInterval:
    compliant: 10m
    noncompliant: 30s
  object-templates-raw: |
    - complianceType: musthave
      objectDefinition:
        apiVersion: ocs.openshift.io/v1
        kind: StorageCluster
        metadata:
          name: ocs-storagecluster
          namespace: openshift-storage
        spec:
          arbiter: {}
          encryption:
            kms: {}
          externalStorage: {}
          managedResources:
            cephObjectStoreUsers: {}
            cephCluster: {}
            cephBlockPools: {}
            cephNonResilientPools: {}
            cephObjectStores: {}
            cephFilesystems: {}
            cephRBDMirror: {}
            cephToolbox: {}
            cephDashboard: {}
            cephConfig: {}
          mirroring: {}
          multiCloudGateway:
            reconcileStrategy: standalone
