object-templates-raw: |
  {{ `{{- range (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "").items }}` }}
  {{ `{{- $mode := index (.metadata.labels | default dict) "autoshift.io/global-hub-deploy-mode" }}` }}
  {{ `{{- if $mode }}` }}
  - complianceType: musthave
    objectDefinition:
      apiVersion: cluster.open-cluster-management.io/v1
      kind: ManagedCluster
      metadata:
        name: {{ `{{ .metadata.name }}` }}
        labels:
          global-hub.open-cluster-management.io/deploy-mode: {{ `{{ $mode }}` }}
  {{ `{{- end }}` }}
  {{ `{{- end }}` }}
