// Package resolver wraps the ACM go-template-utils library to resolve hub
// templates offline using synthetic ManagedClusterLabels.
package resolver

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/stolostron/go-template-utils/v7/pkg/templates"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	fakedynamic "k8s.io/client-go/dynamic/fake"
	fakeclientset "k8s.io/client-go/kubernetes/fake"
	sigsyaml "sigs.k8s.io/yaml"
)

// Resolver wraps the ACM TemplateResolver for offline hub template resolution.
type Resolver struct {
	inner *templates.TemplateResolver
}

// NewResolver creates a Resolver with fake Kubernetes clients. Hub templates
// only use `index .ManagedClusterLabels` and Sprig — no actual API calls are
// made. The fake clients satisfy the constructor's interface requirements.
//
// localResources is a list of Kubernetes objects (e.g. ConfigMaps) that the
// resolver can return for `lookup`/`fromConfigMap` calls. Pass nil for
// hub-template-only resolution (Phase 1). Phase 2 will populate this with
// ConfigMaps generated by the cluster-config-maps chart.
func NewResolver(localResources []unstructured.Unstructured) (*Resolver, error) {
	scheme := runtime.NewScheme()
	dynClient := fakedynamic.NewSimpleDynamicClient(scheme)
	discClient := fakeclientset.NewSimpleClientset().Discovery()

	tr, err := templates.NewResolverWithClients(
		dynClient,
		discClient,
		templates.Config{
			StartDelim:            "{{hub",
			StopDelim:             "hub}}",
			AdditionalIndentation: 8,
		},
	)
	if err != nil {
		return nil, fmt.Errorf("create template resolver: %w", err)
	}

	if len(localResources) > 0 {
		tr.WithLocalResources(localResources)
	}

	return &Resolver{inner: tr}, nil
}

// HubContext is the template context struct passed to the ACM resolver. The
// field names must be exported and match what hub templates reference:
// .ManagedClusterName, .ManagedClusterLabels.
type HubContext struct {
	ManagedClusterName   string
	ManagedClusterLabels map[string]string
}

// ResolvePolicyResult holds the outcome of resolving one multi-document YAML.
type ResolvePolicyResult struct {
	Resolved string   // the reassembled YAML (resolved where possible)
	Errors   []string // per-document resolution errors (non-fatal)
}

// ResolvePolicy takes raw multi-document YAML (from `helm template`), finds
// Policy documents, resolves their hub templates using the provided context,
// and returns the fully-resolved multi-document YAML.
//
// Non-Policy documents (Placement, PlacementBinding) are passed through
// unchanged. Spoke-side `{{ ... }}` templates are untouched because the
// resolver is configured with `{{hub`/`hub}}` delimiters.
//
// Resolution errors on individual Policy documents are collected as warnings
// rather than failing the entire chart. This allows charts with some
// `{{hub lookup ... hub}}` calls (which fail without real API resources) to
// still contribute their successfully-resolved Policy documents.
func (r *Resolver) ResolvePolicy(rawYAML string, ctx HubContext) ResolvePolicyResult {
	docs := splitYAMLDocuments(rawYAML)
	var resolved []string
	var errs []string

	for _, doc := range docs {
		doc = strings.TrimSpace(doc)
		if doc == "" {
			continue
		}

		// Parse to check the kind field.
		var obj map[string]interface{}
		if err := sigsyaml.Unmarshal([]byte(doc), &obj); err != nil {
			// If it doesn't parse as YAML (e.g. a comment block), pass through.
			resolved = append(resolved, doc)
			continue
		}

		kind, _ := obj["kind"].(string)
		if kind != "Policy" {
			// Placement, PlacementBinding, etc. — pass through unchanged.
			resolved = append(resolved, doc)
			continue
		}

		policyName, _ := nestedString(obj, "metadata", "name")

		// JSON-marshal the Policy for the resolver (it expects JSON input).
		jsonBytes, err := json.Marshal(obj)
		if err != nil {
			errs = append(errs, fmt.Sprintf("%s: marshal to JSON: %v", policyName, err))
			resolved = append(resolved, doc) // pass through the original
			continue
		}

		result, err := r.inner.ResolveTemplate(jsonBytes, ctx, &templates.ResolveOptions{})
		if err != nil {
			errs = append(errs, fmt.Sprintf("%s: %v", policyName, err))
			resolved = append(resolved, doc) // pass through the original
			continue
		}

		// Convert resolved JSON back to YAML.
		resolvedYAML, err := sigsyaml.JSONToYAML(result.ResolvedJSON)
		if err != nil {
			errs = append(errs, fmt.Sprintf("%s: convert to YAML: %v", policyName, err))
			resolved = append(resolved, doc)
			continue
		}

		resolved = append(resolved, string(resolvedYAML))
	}

	return ResolvePolicyResult{
		Resolved: strings.Join(resolved, "---\n"),
		Errors:   errs,
	}
}

// nestedString extracts a string from a nested map path.
func nestedString(obj map[string]interface{}, keys ...string) (string, bool) {
	current := obj
	for i, k := range keys {
		v, ok := current[k]
		if !ok {
			return "", false
		}
		if i == len(keys)-1 {
			s, ok := v.(string)
			return s, ok
		}
		next, ok := v.(map[string]interface{})
		if !ok {
			return "", false
		}
		current = next
	}
	return "", false
}

// splitYAMLDocuments splits a multi-document YAML string on `---` boundaries.
func splitYAMLDocuments(raw string) []string {
	// Split on lines that are exactly "---" (possibly with trailing whitespace).
	var docs []string
	current := strings.Builder{}

	for _, line := range strings.Split(raw, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "---" {
			if current.Len() > 0 {
				docs = append(docs, current.String())
				current.Reset()
			}
			continue
		}
		current.WriteString(line)
		current.WriteString("\n")
	}
	if current.Len() > 0 {
		docs = append(docs, current.String())
	}

	return docs
}
