{{- $policyName := "policy-vault-secrets-connections" }}
{{- $placementName := "placement-policy-vault-secrets-connections" }}

apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $policyName }}
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
{{ if (($.Values.autoshift).dryRun) }}
  remediationAction: inform
{{ end }}
  disabled: false
  dependencies:
    - name: policy-vault-secrets-operator-install
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: vault-secrets-vault-connection
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates-raw: |
            {{ "{{hub" }} $configs := index (index (fromConfigMap "{{ $.Values.policy_namespace }}" (print .ManagedClusterName ".rendered-config") "config" | default "" | fromYaml) "vault-secrets" | default dict) {{ "hub}}" }}
            {{ "{{hub" }} range $idx, $auth := $configs.auth {{ "hub}}" }}
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: secrets.hashicorp.com/v1beta1
                kind: VaultConnection
                metadata:
                  name: "{{ "{{hub" }} printf "%s-connection" $auth.instanceName {{ "hub}}" }}"
                  namespace: "{{ "{{hub" }} $auth.secretsNamespace {{ "hub}}" }}"
                spec:
                  address: "{{ "{{hub" }} $auth.vaultUrl {{ "hub}}" }}"
                  skipTLSVerify: true
            {{ "{{hub" }} end {{ "hub}}" }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: vault-secrets-vault-auth
        spec:
          remediationAction: enforce
          severity: high
          object-templates-raw: |
            {{ "{{hub" }} $configs := index (index (fromConfigMap "{{ $.Values.policy_namespace }}" (print .ManagedClusterName ".rendered-config") "config" | default "" | fromYaml) "vault-secrets" | default dict) {{ "hub}}" }}
            {{ "{{hub" }} range $idx, $auth := $configs.auth {{ "hub}}" }}
            - complianceType: mustonlyhave
              objectDefinition:
                kind: VaultAuth
                apiVersion: secrets.hashicorp.com/v1beta1
                metadata:
                  name: "{{ "{{hub" }} print $auth.instanceName "-auth" {{ "hub}}" }}"
                  namespace: "{{ "{{hub" }} $auth.secretsNamespace {{ "hub}}" }}"
                spec:
                  jwt:
                    role: "{{ "{{hub" }} $auth.role {{ "hub}}" }}"
                    audiences:
                      - "{{ "{{hub" }} printf "https://%s:6443/openid/v1/jwks" $auth.oidcApi {{ "hub}}" }}"
                      - https://kubernetes.default.svc
                    serviceAccount: "{{ "{{hub" }} $auth.serviceAccount {{ "hub}}" }}"
                  method: jwt
                  mount: "{{ "{{hub" }} $auth.authMount {{ "hub}}" }}"
                  vaultConnectionRef: "{{ "{{hub" }} print $auth.instanceName "-connection" {{ "hub}}" }}"
            {{ "{{hub" }} end {{ "hub}}" }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ $placementName }}
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/vault-secrets'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ $placementName }}
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: {{ $placementName }}
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: {{ $policyName }}
    apiGroup: policy.open-cluster-management.io
    kind: Policy