{{- $policyName := "policy-vault-secrets-namespace" }}
{{- $placementName := "placement-policy-vault-secrets-namespace" }}

apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $policyName }}
  namespace: {{ .Values.policy_namespace }}
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: vault-secrets-secrets-ns
        spec:
          remediationAction: enforce
          severity: high
          object-templates-raw: |
            {{ "{{hub" }} $configs := index (index (fromConfigMap "{{ $.Values.policy_namespace }}" (print .ManagedClusterName ".rendered-config") "config" | default "" | fromYaml) "vault-secrets" | default dict) {{ "hub}}" }}
            {{ "{{hub" }} range $idx, $auth := $configs.auth {{ "hub}}" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: "{{ "{{hub" }} $auth.secretsNamespace {{ "hub}}" }}"
            {{ "{{hub" }} end {{ "hub}}" }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: vault-secrets-reader-service-account
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ServiceAccount
                metadata:
                  name: secret-reader
                  namespace: {{ .Values.policy_namespace }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: vault-secrets-reader-role
        spec:
          remediationAction: enforce
          severity: high
          object-templates-raw: |
            {{ "{{hub" }} $configs := index (index (fromConfigMap "{{ $.Values.policy_namespace }}" (print .ManagedClusterName ".rendered-config") "config" | default "" | fromYaml) "vault-secrets" | default dict) {{ "hub}}" }}
            {{ "{{hub" }} range $idx, $auth := $configs.auth {{ "hub}}" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: secret-reader-role
                  namespace: "{{ "{{hub" }} $auth.secretsNamespace {{ "hub}}" }}"
                rules:
                  - apiGroups: [""]
                    resources: ["secrets"]
                    verbs: ["get", "list", "watch"]
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: secret-reader-configmap-role
                  namespace: {{ .Values.policy_namespace }}
                rules:
                  - apiGroups: [""]
                    resources: ["configmaps"]
                    verbs: ["get", "list", "watch"]
            {{ "{{hub" }} end {{ "hub}}" }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: vault-secrets-reader-clusterrolebinding
        spec:
          remediationAction: enforce
          severity: high
          object-templates-raw: |
            {{ "{{hub" }} $configs := index (index (fromConfigMap "{{ $.Values.policy_namespace }}" (print .ManagedClusterName ".rendered-config") "config" | default "" | fromYaml) "vault-secrets" | default dict) {{ "hub}}" }}
            {{ "{{hub" }} range $idx, $auth := $configs.auth {{ "hub}}" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: secret-reader-binding
                  namespace: "{{ "{{hub" }} $auth.secretsNamespace {{ "hub}}" }}"
                subjects:
                  - kind: ServiceAccount
                    name: secret-reader
                    namespace: {{ .Values.policy_namespace }}
                roleRef:
                  kind: Role
                  name: secret-reader-role
                  apiGroup: rbac.authorization.k8s.io
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: secret-reader-configmap-binding
                  namespace: {{ .Values.policy_namespace }}
                subjects:
                  - kind: ServiceAccount
                    name: secret-reader
                    namespace: {{ .Values.policy_namespace }}
                roleRef:
                  kind: Role
                  name: secret-reader-configmap-role
                  apiGroup: rbac.authorization.k8s.io
            {{ "{{hub" }} end {{ "hub}}" }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: vault-secrets-managedcluster-list-cr
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRole
                metadata:
                  name: managedcluster-reader
                rules:
                  - apiGroups: ["cluster.open-cluster-management.io"]
                    resources: ["managedclusters"]
                    verbs: ["get", "list", "watch"]
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: vault-secrets-managedcluster-list-rolebinding
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: managedcluster-reader-binding
                subjects:
                  - kind: ServiceAccount
                    name: secret-reader
                    namespace: {{ .Values.policy_namespace }}
                roleRef:
                  kind: ClusterRole
                  name: managedcluster-reader
                  apiGroup: rbac.authorization.k8s.io
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ $placementName }}
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/vault-secrets'
              operator: In
              values:
                - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ $placementName }}
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: {{ $placementName }}
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: {{ $policyName }}
    apiGroup: policy.open-cluster-management.io
    kind: Policy