{{- $policyName := "policy-vault-secrets-cabundle" }}
{{- $policyNamespace := $.Values.policy_namespace }}
{{- $placementName := "placement-policy-vault-secrets-cabundle" }}

apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ $policyName }}
  namespace: {{ .Values.policy_namespace }}
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: vault-secrets-cabundle
        spec:
          remediationAction: enforce
          severity: high
          object-templates-raw: |
            {{ "{{hub" }} $configs := fromConfigMap "{{ $.Values.policy_namespace }}" (print .ManagedClusterName ".rendered-config") "config" | default "" | fromYaml {{ "hub}}" }}
            {{ "{{hub" }} $vault := index $configs "vault-secrets" {{ "hub}}" }}
            {{ "{{hub" }} range $idx, $auth := $vault.auth {{ "hub}}" }}
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: ca-bundle
                  namespace: "{{ "{{hub" }} $auth.secretsNamespace {{ "hub}}" }}"
                data:
                  ca.crt: |
                    {{ "{{hub" }} index $configs "user-ca-bundle" | b64enc | autoindent {{ "hub}}" }}
            {{ "{{hub" }} end {{ "hub}}" }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ $placementName }}
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/vault-secrets'
              operator: In
              values:
                - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ $placementName }}
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: {{ $placementName }}
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: {{ $policyName }}
    apiGroup: policy.open-cluster-management.io
    kind: Policy
